// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package unifieddatalibrary

import (
	"context"
	"net/http"
	"net/url"
	"time"

	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apijson"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apiquery"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/requestconfig"
	"github.com/stainless-sdks/unifieddatalibrary-go/option"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/pagination"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/param"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/resp"
)

// AirtaskingorderService contains methods and other services that help with
// interacting with the unifieddatalibrary API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewAirtaskingorderService] method instead.
type AirtaskingorderService struct {
	Options []option.RequestOption
}

// NewAirtaskingorderService generates a new service that applies the given options
// to each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewAirtaskingorderService(opts ...option.RequestOption) (r AirtaskingorderService) {
	r = AirtaskingorderService{}
	r.Options = opts
	return
}

// Service operation to dynamically query data by a variety of query parameters not
// specified in this API documentation. See the queryhelp operation
// (/udl/&lt;datatype&gt;/queryhelp) for more details on valid/required query
// parameter information.
func (r *AirtaskingorderService) List(ctx context.Context, query AirtaskingorderListParams, opts ...option.RequestOption) (res *pagination.OffsetPage[AirtaskingorderAbridged], err error) {
	var raw *http.Response
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	path := "udl/airtaskingorder"
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// Service operation to dynamically query data by a variety of query parameters not
// specified in this API documentation. See the queryhelp operation
// (/udl/&lt;datatype&gt;/queryhelp) for more details on valid/required query
// parameter information.
func (r *AirtaskingorderService) ListAutoPaging(ctx context.Context, query AirtaskingorderListParams, opts ...option.RequestOption) *pagination.OffsetPageAutoPager[AirtaskingorderAbridged] {
	return pagination.NewOffsetPageAutoPager(r.List(ctx, query, opts...))
}

// Beta Version Air Tasking Order: The ATO is used to task air missions, assign
// cross force tasking as well as intraservice tasking.
type AirtaskingorderAbridged struct {
	// The effective begin time for this ATO in ISO 8601 UTC format with millisecond
	// precision.
	BeginTs time.Time `json:"beginTs,required" format:"date-time"`
	// Classification marking of the data in IC/CAPCO Portion-marked format.
	ClassificationMarking string `json:"classificationMarking,required"`
	// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
	//
	// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
	// may include both real and simulated data.
	//
	// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
	// events, and analysis.
	//
	// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
	// datasets.
	//
	// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
	// requirements, and for validating technical, functional, and performance
	// characteristics.
	//
	// Any of "REAL", "TEST", "SIMULATED", "EXERCISE".
	DataMode AirtaskingorderAbridgedDataMode `json:"dataMode,required"`
	// Specifies the unique operation or exercise name, nickname, or codeword assigned
	// to a joint exercise or operation plan.
	OpExerName string `json:"opExerName,required"`
	// Source of the data.
	Source string `json:"source,required"`
	// Unique identifier of the record, auto-generated by the system.
	ID string `json:"id"`
	// The indicator specifying an affirmative or a negatice condition for this
	// message.
	AckReqInd string `json:"ackReqInd"`
	// Specifies textual data amplifying the data contained in the acknowledgement
	// requirement indicator (ackRedInd) field or the unit required to acknowledge.
	AckUnitInstructions string `json:"ackUnitInstructions"`
	// A collection that specifies the tasked country, tasked service, unit and mission
	// level tasking for this ATO.
	AcMsnTasking []AirtaskingorderAbridgedAcMsnTasking `json:"acMsnTasking"`
	// Time the row was created in the database.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Application user who created the row in the database.
	CreatedBy string `json:"createdBy"`
	// The effective end time for this ATO in ISO 8601 UTC format with millisecond
	// precision.
	EndTs time.Time `json:"endTs" format:"date-time"`
	// A collection that details special instructions, important information, guidance,
	// and amplifying information regarding this ATO.
	GenText []AirtaskingorderAbridgedGenText `json:"genText"`
	// The month in which the message originated.
	MsgMonth string `json:"msgMonth"`
	// The identifier of the originator of the message.
	MsgOriginator string `json:"msgOriginator"`
	// The qualifier which caveats the message status.
	MsgQualifier string `json:"msgQualifier"`
	// The unique message identifier sequentially assigned by the originator.
	MsgSn string `json:"msgSN"`
	// A collection that specifies the naval flight operations for this ATO.
	NavalFltOps []AirtaskingorderAbridgedNavalFltOp `json:"navalFltOps"`
	// Originating system or organization which produced the data, if different from
	// the source. The origin may be different than the source if the source was a
	// mediating system which forwarded the data on behalf of the origin system. If
	// null, the source may be assumed to be the origin.
	Origin string `json:"origin"`
	// The originating source network on which this record was created, auto-populated
	// by the system.
	OrigNetwork string `json:"origNetwork"`
	// Optional URI location in the document repository of the raw file parsed by the
	// system to produce this record. To download the raw file, prepend
	// https://udl-hostname/scs/download?id= to this value.
	RawFileUri string `json:"rawFileURI"`
	// The source data library from which this record was received. This could be a
	// remote or tactical UDL or another data library. If null, the record should be
	// assumed to have originated from the primary Enterprise UDL.
	SourceDl string `json:"sourceDL"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		BeginTs               resp.Field
		ClassificationMarking resp.Field
		DataMode              resp.Field
		OpExerName            resp.Field
		Source                resp.Field
		ID                    resp.Field
		AckReqInd             resp.Field
		AckUnitInstructions   resp.Field
		AcMsnTasking          resp.Field
		CreatedAt             resp.Field
		CreatedBy             resp.Field
		EndTs                 resp.Field
		GenText               resp.Field
		MsgMonth              resp.Field
		MsgOriginator         resp.Field
		MsgQualifier          resp.Field
		MsgSn                 resp.Field
		NavalFltOps           resp.Field
		Origin                resp.Field
		OrigNetwork           resp.Field
		RawFileUri            resp.Field
		SourceDl              resp.Field
		ExtraFields           map[string]resp.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AirtaskingorderAbridged) RawJSON() string { return r.JSON.raw }
func (r *AirtaskingorderAbridged) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
//
// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
// may include both real and simulated data.
//
// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
// events, and analysis.
//
// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
// datasets.
//
// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
// requirements, and for validating technical, functional, and performance
// characteristics.
type AirtaskingorderAbridgedDataMode string

const (
	AirtaskingorderAbridgedDataModeReal      AirtaskingorderAbridgedDataMode = "REAL"
	AirtaskingorderAbridgedDataModeTest      AirtaskingorderAbridgedDataMode = "TEST"
	AirtaskingorderAbridgedDataModeSimulated AirtaskingorderAbridgedDataMode = "SIMULATED"
	AirtaskingorderAbridgedDataModeExercise  AirtaskingorderAbridgedDataMode = "EXERCISE"
)

// Collection that specifies the tasked country, tasked service, unit and mission
// level tasking for this ATO.
type AirtaskingorderAbridgedAcMsnTasking struct {
	// The country code responsible for conducting this aircraft mission tasking for
	// the exercise or operation.
	CountryCode string `json:"countryCode,required"`
	// The service tasked with conducting this aircraft mission tasking for the
	// exercise or operation.
	TaskedService string `json:"taskedService,required"`
	// The designator of the unit that is tasked to perform this aircraft mission
	// tasking.
	UnitDesignator string `json:"unitDesignator,required"`
	// A collection of aircraft mission location information for this aircraft mission
	// tasking.
	AcMsnLocSeg []AirtaskingorderAbridgedAcMsnTaskingAcMsnLocSeg `json:"acMsnLocSeg"`
	// The readiness status expressed in time (minutes) for an aircraft to be airborne
	// after the launch order is received or the time required for a missile unit to
	// assume battle stations.
	AlertStatus int64 `json:"alertStatus"`
	// The AMC number assigned to identify one aircraft from another.
	AmcMsnNum string `json:"amcMsnNum"`
	// WGS-84 latitude of the departure location, in degrees. -90 to 90 degrees
	// (negative values south of equator) for this tasked air mission.
	DepLocLat float64 `json:"depLocLat"`
	// WGS-84 longitude of the departure location, in degrees. -180 to 180 degrees
	// (negative values west of Prime Meridian) for this tasked air mission.
	DepLocLon float64 `json:"depLocLon"`
	// The location or name specified for the departure of the tasked air mission.
	DepLocName string `json:"depLocName"`
	// The departure location specified in UTM (100 meter) coordinates for the tasked
	// air mission.
	DepLocUtm string `json:"depLocUTM"`
	// The time of departure for the tasked air mission in ISO8601 UTC format with
	// millisecond precision.
	DepTime time.Time `json:"depTime" format:"date-time"`
	// A collection of the individual aircraft assigned to this aircraft mission
	// tasking.
	IndAcTasking []AirtaskingorderAbridgedAcMsnTaskingIndAcTasking `json:"indACTasking"`
	// The commander responsible for the planning and execution of the forces necessary
	// to achieve desired objectives.
	MsnCommander string `json:"msnCommander"`
	// The mission number assigned to this mission.
	MsnNum string `json:"msnNum"`
	// The identifier for the composite set of missions for this operation/exercise.
	PkgID string `json:"pkgId"`
	// The code for the preferred type or designator for a tasked air mission.
	PriMsnType string `json:"priMsnType"`
	// An array of WGS-84 latitude of the recovery locations, in degrees. -90 to 90
	// degrees (negative values south of equator) for this tasked air mission.
	RcvyLocLat []float64 `json:"rcvyLocLat"`
	// An array of WGS-84 longitude of the recovery locations, in degrees. -180 to 180
	// degrees (negative values west of Prime Meridian) for this tasked air mission.
	RcvyLocLon []float64 `json:"rcvyLocLon"`
	// An array of locations specified for the recovery of the tasked air mission
	// represented by varying formats.
	RcvyLocName []string `json:"rcvyLocName"`
	// An array of recovery locations specified in UTM (100 meter) coordinates for the
	// tasked air mission.
	RcvyLocUtm []string `json:"rcvyLocUTM"`
	// An array of recovery times for the tasked air mission in ISO8601 UTC format with
	// millisecond precision.
	RcvyTime []time.Time `json:"rcvyTime" format:"date-time"`
	// An indicator of whether a mission is or will be a residual mission.
	ResMsnInd string `json:"resMsnInd" format:"char"`
	// The code for the alternative type of a tasked air mission.
	SecMsnType string `json:"secMsnType"`
	// The tasked units location expressed as an ICAO or a place name.
	UnitLocName string `json:"unitLocName"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		CountryCode    resp.Field
		TaskedService  resp.Field
		UnitDesignator resp.Field
		AcMsnLocSeg    resp.Field
		AlertStatus    resp.Field
		AmcMsnNum      resp.Field
		DepLocLat      resp.Field
		DepLocLon      resp.Field
		DepLocName     resp.Field
		DepLocUtm      resp.Field
		DepTime        resp.Field
		IndAcTasking   resp.Field
		MsnCommander   resp.Field
		MsnNum         resp.Field
		PkgID          resp.Field
		PriMsnType     resp.Field
		RcvyLocLat     resp.Field
		RcvyLocLon     resp.Field
		RcvyLocName    resp.Field
		RcvyLocUtm     resp.Field
		RcvyTime       resp.Field
		ResMsnInd      resp.Field
		SecMsnType     resp.Field
		UnitLocName    resp.Field
		ExtraFields    map[string]resp.Field
		raw            string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AirtaskingorderAbridgedAcMsnTasking) RawJSON() string { return r.JSON.raw }
func (r *AirtaskingorderAbridgedAcMsnTasking) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Collection of aircraft mission location information for this aircraft mission
// tasking.
type AirtaskingorderAbridgedAcMsnTaskingAcMsnLocSeg struct {
	// The start time of this mission in ISO 8601 UTC format with millisecond
	// precision.
	StartTime time.Time `json:"startTime,required" format:"date-time"`
	// The code for the priority assigned to this mission.
	AirMsnPri string `json:"airMsnPri"`
	// The altitude for this mission represented as hundreds of feet above MSL.
	Alt int64 `json:"alt"`
	// The radius of the circle around the location being reported in feet.
	AreaGeoRad int64 `json:"areaGeoRad"`
	// The end time of this mission in ISO 8601 UTC format with millisecond precision.
	EndTime time.Time `json:"endTime" format:"date-time"`
	// The name that identifies the location at which this mission is to be performed.
	// This can be the name of a general target area, orbit, cap point, station, etc.
	MsnLocName string `json:"msnLocName"`
	// The alpha-numeric specified location for this mission specified as a bearing
	// angle in degrees relative to true north and a range in nautical miles (NM).
	MsnLocPtBarT string `json:"msnLocPtBarT"`
	// WGS-84 latitude of the mission location, in degrees. -90 to 90 degrees (negative
	// values south of equator) for this tasked air mission.
	MsnLocPtLat float64 `json:"msnLocPtLat"`
	// WGS-84 longitude of the mission location, in degrees. -180 to 180 degrees
	// (negative values west of Prime Meridian) for this tasked air mission.
	MsnLocPtLon float64 `json:"msnLocPtLon"`
	// The location name for this mission.
	MsnLocPtName string `json:"msnLocPtName"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		StartTime    resp.Field
		AirMsnPri    resp.Field
		Alt          resp.Field
		AreaGeoRad   resp.Field
		EndTime      resp.Field
		MsnLocName   resp.Field
		MsnLocPtBarT resp.Field
		MsnLocPtLat  resp.Field
		MsnLocPtLon  resp.Field
		MsnLocPtName resp.Field
		ExtraFields  map[string]resp.Field
		raw          string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AirtaskingorderAbridgedAcMsnTaskingAcMsnLocSeg) RawJSON() string { return r.JSON.raw }
func (r *AirtaskingorderAbridgedAcMsnTaskingAcMsnLocSeg) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Collection that specifies the naval flight operations for this ATO.
type AirtaskingorderAbridgedAcMsnTaskingIndAcTasking struct {
	// The type and model number for the aircraft. The field may specify a value of an
	// aircraft not yet assigned an aircraft code contained in the aircraft codes list.
	AcftType string `json:"acftType,required"`
	// The call sign assigned to this mission aircraft.
	CallSign string `json:"callSign"`
	// The mode 1 and code of the Identification Friend or FOE (IFF) or Selective
	// Identification Feature (SIF).
	IffSifMode1Code string `json:"iffSifMode1Code"`
	// The mode 2 and code of the Identification Friend or FOE (IFF) or Selective
	// Identification Feature (SIF).
	IffSifMode2Code string `json:"iffSifMode2Code"`
	// The mode 3 and code of the Identification Friend or FOE (IFF) or Selective
	// Identification Feature (SIF).
	IffSifMode3Code string `json:"iffSifMode3Code"`
	// An optional array of link 16 octal track numbers assigned as the primary JTIDS
	// Unit (JU) address for the mission aircraft.
	JuAddress []int64 `json:"juAddress"`
	// The Link 16 abbreviated call sign assigned to the ACA. This is normally the
	// first and last letter and the last two numbers of the call sign.
	Link16CallSign string `json:"link16CallSign"`
	// The number of aircraft participating in this mission.
	NumAcft int64 `json:"numAcft"`
	// The code that indicates the ordinance mix carried on this mission aircraft.
	PriConfigCode string `json:"priConfigCode"`
	// The code for the secondary ordinance mix carried on this mission aircraft.
	SecConfigCode string `json:"secConfigCode"`
	// The TACAN channel assigned to this mission aircraft.
	TacanChan int64 `json:"tacanChan"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		AcftType        resp.Field
		CallSign        resp.Field
		IffSifMode1Code resp.Field
		IffSifMode2Code resp.Field
		IffSifMode3Code resp.Field
		JuAddress       resp.Field
		Link16CallSign  resp.Field
		NumAcft         resp.Field
		PriConfigCode   resp.Field
		SecConfigCode   resp.Field
		TacanChan       resp.Field
		ExtraFields     map[string]resp.Field
		raw             string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AirtaskingorderAbridgedAcMsnTaskingIndAcTasking) RawJSON() string { return r.JSON.raw }
func (r *AirtaskingorderAbridgedAcMsnTaskingIndAcTasking) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Collection that details special instructions, important information, guidance,
// and amplifying information regarding this ATO.
type AirtaskingorderAbridgedGenText struct {
	// The free text that describes the information specific to the text indicator.
	Text string `json:"text"`
	// The indicator for the general text block. Examples include "OPENING REMARKS" and
	// "GENERAL SPINS INFORMATION".
	TextInd string `json:"textInd"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		Text        resp.Field
		TextInd     resp.Field
		ExtraFields map[string]resp.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AirtaskingorderAbridgedGenText) RawJSON() string { return r.JSON.raw }
func (r *AirtaskingorderAbridgedGenText) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Collection that specifies the naval flight operations for this ATO.
type AirtaskingorderAbridgedNavalFltOp struct {
	// The name of a ship or maritime vessel. Specify UNKNOWN if name is not known.
	ShipName string `json:"shipName,required"`
	// The time when flight operations begin in ISO8601 UTC format with millisecond
	// precision.
	FltOpStart time.Time `json:"fltOpStart" format:"date-time"`
	// The time when flight operations end in ISO8601 UTC format with millisecond
	// precision.
	FltOpStop time.Time `json:"fltOpStop" format:"date-time"`
	// An array of times at which an aircraft will be launched and/or recovered in
	// ISO8601 UTC format with millisecond precision.
	SchdLaunchRcvyTime []time.Time `json:"schdLaunchRcvyTime" format:"date-time"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		ShipName           resp.Field
		FltOpStart         resp.Field
		FltOpStop          resp.Field
		SchdLaunchRcvyTime resp.Field
		ExtraFields        map[string]resp.Field
		raw                string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AirtaskingorderAbridgedNavalFltOp) RawJSON() string { return r.JSON.raw }
func (r *AirtaskingorderAbridgedNavalFltOp) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type AirtaskingorderListParams struct {
	FirstResult param.Opt[int64] `query:"firstResult,omitzero" json:"-"`
	MaxResults  param.Opt[int64] `query:"maxResults,omitzero" json:"-"`
	paramObj
}

// IsPresent returns true if the field's value is not omitted and not the JSON
// "null". To check if this field is omitted, use [param.IsOmitted].
func (f AirtaskingorderListParams) IsPresent() bool { return !param.IsOmitted(f) && !f.IsNull() }

// URLQuery serializes [AirtaskingorderListParams]'s query parameters as
// `url.Values`.
func (r AirtaskingorderListParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
