// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package unifieddatalibrary

import (
	"context"
	"net/http"
	"net/url"
	"time"

	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apijson"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apiquery"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/requestconfig"
	"github.com/stainless-sdks/unifieddatalibrary-go/option"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/pagination"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/param"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/resp"
)

// EphemerisAttitudeDataService contains methods and other services that help with
// interacting with the unifieddatalibrary API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewEphemerisAttitudeDataService] method instead.
type EphemerisAttitudeDataService struct {
	Options []option.RequestOption
	History EphemerisAttitudeDataHistoryService
}

// NewEphemerisAttitudeDataService generates a new service that applies the given
// options to each request. These options are applied after the parent client's
// options (if there is one), and before any request-specific options.
func NewEphemerisAttitudeDataService(opts ...option.RequestOption) (r EphemerisAttitudeDataService) {
	r = EphemerisAttitudeDataService{}
	r.Options = opts
	r.History = NewEphemerisAttitudeDataHistoryService(opts...)
	return
}

// Service operation to dynamically query data by a variety of query parameters not
// specified in this API documentation. See the queryhelp operation
// (/udl/&lt;datatype&gt;/queryhelp) for more details on valid/required query
// parameter information.
func (r *EphemerisAttitudeDataService) List(ctx context.Context, query EphemerisAttitudeDataListParams, opts ...option.RequestOption) (res *pagination.OffsetPage[AttitudeDataAbridged], err error) {
	var raw *http.Response
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithResponseInto(&raw)}, opts...)
	path := "udl/attitudedata"
	cfg, err := requestconfig.NewRequestConfig(ctx, http.MethodGet, path, query, &res, opts...)
	if err != nil {
		return nil, err
	}
	err = cfg.Execute()
	if err != nil {
		return nil, err
	}
	res.SetPageConfig(cfg, raw)
	return res, nil
}

// Service operation to dynamically query data by a variety of query parameters not
// specified in this API documentation. See the queryhelp operation
// (/udl/&lt;datatype&gt;/queryhelp) for more details on valid/required query
// parameter information.
func (r *EphemerisAttitudeDataService) ListAutoPaging(ctx context.Context, query EphemerisAttitudeDataListParams, opts ...option.RequestOption) *pagination.OffsetPageAutoPager[AttitudeDataAbridged] {
	return pagination.NewOffsetPageAutoPager(r.List(ctx, query, opts...))
}

// Service operation to return the count of records satisfying the specified query
// parameters. This operation is useful to determine how many records pass a
// particular query criteria without retrieving large amounts of data. See the
// queryhelp operation (/udl/&lt;datatype&gt;/queryhelp) for more details on
// valid/required query parameter information.
func (r *EphemerisAttitudeDataService) Count(ctx context.Context, query EphemerisAttitudeDataCountParams, opts ...option.RequestOption) (res *string, err error) {
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	path := "udl/attitudedata/count"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// These services provide operations for posting and querying attitude of on-orbit
// objects. Attitude describes the orientation of an object, which can be
// represented by quaternions or euler angles. The AttitudeSet ID (asId) identifies
// the 'AttitudeSet' record which contains details of the underlying data as well
// as a collection of attitude points. Points must be retrieved by first
// identifying a desired AttitudeSet and pulling its points by that AttitudeSet ID
// 'asId'.
type AttitudeDataAbridged struct {
	// Classification marking of the data in IC/CAPCO Portion-marked format.
	ClassificationMarking string `json:"classificationMarking,required"`
	// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
	//
	// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
	// may include both real and simulated data.
	//
	// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
	// events, and analysis.
	//
	// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
	// datasets.
	//
	// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
	// requirements, and for validating technical, functional, and performance
	// characteristics.
	//
	// Any of "REAL", "TEST", "SIMULATED", "EXERCISE".
	DataMode AttitudeDataAbridgedDataMode `json:"dataMode,required"`
	// Source of the data.
	Source string `json:"source,required"`
	// Time associated with this attitude record, in ISO 8601 UTC format, with
	// microsecond precision.
	Ts time.Time `json:"ts,required" format:"date-time"`
	// Unique identifier of the record, auto-generated by the system.
	ID string `json:"id"`
	// Unique identifier of the parent AttitudeSet associated with this record.
	AsID string `json:"asId"`
	// Coning angle in degrees.
	ConingAngle float64 `json:"coningAngle"`
	// Time the row was created in the database, auto-populated by the system.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Application user who created the row in the database, auto-populated by the
	// system.
	CreatedBy string `json:"createdBy"`
	// Precession axis declination (ECI J2000 frame) in degrees.
	Declination float64 `json:"declination"`
	// Unique identifier of the on-orbit satellite to which this attitude record
	// applies.
	IDOnOrbit string `json:"idOnOrbit"`
	// Label specifying type of rotational motion of target.
	MotionType string `json:"motionType"`
	// Originating system or organization which produced the data, if different from
	// the source. The origin may be different than the source if the source was a
	// mediating system which forwarded the data on behalf of the origin system. If
	// null, the source may be assumed to be the origin.
	Origin string `json:"origin"`
	// The originating source network on which this record was created, auto-populated
	// by the system.
	OrigNetwork string `json:"origNetwork"`
	// Optional identifier provided by the record source to indicate the target object
	// of this attitude record. This may be an internal identifier and not necessarily
	// map to a valid satellite number.
	OrigObjectID string `json:"origObjectId"`
	// Precession period in seconds.
	PrecPeriod float64 `json:"precPeriod"`
	// Quaternion vector component 1.
	Q1 float64 `json:"q1"`
	// Derivative of quaternion vector component 1.
	Q1Dot float64 `json:"q1Dot"`
	// Quaternion vector component 2.
	Q2 float64 `json:"q2"`
	// Derivative of quaternion vector component 2.
	Q2Dot float64 `json:"q2Dot"`
	// Quaternion vector component 3.
	Q3 float64 `json:"q3"`
	// Derivative of quaternion vector component 3.
	Q3Dot float64 `json:"q3Dot"`
	// Quaternion scalar component.
	Qc float64 `json:"qc"`
	// Derivative of quaternion scalar component.
	QcDot float64 `json:"qcDot"`
	// Precession axis right ascension (ECI J2000 frame) in degrees.
	Ra float64 `json:"ra"`
	// Satellite/catalog number of the on-orbit object to which this attitude record
	// applies.
	SatNo int64 `json:"satNo"`
	// Spin period in seconds.
	SpinPeriod float64 `json:"spinPeriod"`
	// Array of X body rotation Euler angle(s), in degrees (-180 to 180). For repeated
	// axis rotations, the array elements should be placed in the order that the angles
	// apply in the sequence.
	XAngle []float64 `json:"xAngle"`
	// Array of X body rotation rate(s), in degrees per second. For repeated axis
	// rotations, the array elements should be placed in the order that the rates apply
	// in the sequence. Attitude rates are expressed in frame1 with respect to frame2.
	XRate []float64 `json:"xRate"`
	// Array of Y body rotation Euler angle(s), in degrees (-180 to 180). For repeated
	// axis rotations, the array elements should be placed in the order that the angles
	// apply in the sequence.
	YAngle []float64 `json:"yAngle"`
	// Array of Y body rotation rate(s), in degrees per second. For repeated axis
	// rotations, the array elements should be placed in the order that the rates apply
	// in the sequence. Attitude rates are expressed in frame1 with respect to frame2.
	YRate []float64 `json:"yRate"`
	// Array of Z body rotation Euler angle(s), in degrees (-180 to 180). For repeated
	// axis rotations, the array elements should be placed in the order that the angles
	// apply in the sequence.
	ZAngle []float64 `json:"zAngle"`
	// Array of Z body rotation rate(s), in degrees per second. For repeated axis
	// rotations, the array elements should be placed in the order that the rates apply
	// in the sequence Attitude rates are expressed in frame1 with respect to frame2.
	ZRate []float64 `json:"zRate"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		ClassificationMarking resp.Field
		DataMode              resp.Field
		Source                resp.Field
		Ts                    resp.Field
		ID                    resp.Field
		AsID                  resp.Field
		ConingAngle           resp.Field
		CreatedAt             resp.Field
		CreatedBy             resp.Field
		Declination           resp.Field
		IDOnOrbit             resp.Field
		MotionType            resp.Field
		Origin                resp.Field
		OrigNetwork           resp.Field
		OrigObjectID          resp.Field
		PrecPeriod            resp.Field
		Q1                    resp.Field
		Q1Dot                 resp.Field
		Q2                    resp.Field
		Q2Dot                 resp.Field
		Q3                    resp.Field
		Q3Dot                 resp.Field
		Qc                    resp.Field
		QcDot                 resp.Field
		Ra                    resp.Field
		SatNo                 resp.Field
		SpinPeriod            resp.Field
		XAngle                resp.Field
		XRate                 resp.Field
		YAngle                resp.Field
		YRate                 resp.Field
		ZAngle                resp.Field
		ZRate                 resp.Field
		ExtraFields           map[string]resp.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AttitudeDataAbridged) RawJSON() string { return r.JSON.raw }
func (r *AttitudeDataAbridged) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
//
// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
// may include both real and simulated data.
//
// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
// events, and analysis.
//
// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
// datasets.
//
// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
// requirements, and for validating technical, functional, and performance
// characteristics.
type AttitudeDataAbridgedDataMode string

const (
	AttitudeDataAbridgedDataModeReal      AttitudeDataAbridgedDataMode = "REAL"
	AttitudeDataAbridgedDataModeTest      AttitudeDataAbridgedDataMode = "TEST"
	AttitudeDataAbridgedDataModeSimulated AttitudeDataAbridgedDataMode = "SIMULATED"
	AttitudeDataAbridgedDataModeExercise  AttitudeDataAbridgedDataMode = "EXERCISE"
)

type EphemerisAttitudeDataListParams struct {
	// Unique identifier of the parent AttitudeSet associated with this record. (uuid)
	AsID        string           `query:"asId,required" json:"-"`
	FirstResult param.Opt[int64] `query:"firstResult,omitzero" json:"-"`
	MaxResults  param.Opt[int64] `query:"maxResults,omitzero" json:"-"`
	paramObj
}

// IsPresent returns true if the field's value is not omitted and not the JSON
// "null". To check if this field is omitted, use [param.IsOmitted].
func (f EphemerisAttitudeDataListParams) IsPresent() bool { return !param.IsOmitted(f) && !f.IsNull() }

// URLQuery serializes [EphemerisAttitudeDataListParams]'s query parameters as
// `url.Values`.
func (r EphemerisAttitudeDataListParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type EphemerisAttitudeDataCountParams struct {
	// Unique identifier of the parent AttitudeSet associated with this record. (uuid)
	AsID        string           `query:"asId,required" json:"-"`
	FirstResult param.Opt[int64] `query:"firstResult,omitzero" json:"-"`
	MaxResults  param.Opt[int64] `query:"maxResults,omitzero" json:"-"`
	paramObj
}

// IsPresent returns true if the field's value is not omitted and not the JSON
// "null". To check if this field is omitted, use [param.IsOmitted].
func (f EphemerisAttitudeDataCountParams) IsPresent() bool { return !param.IsOmitted(f) && !f.IsNull() }

// URLQuery serializes [EphemerisAttitudeDataCountParams]'s query parameters as
// `url.Values`.
func (r EphemerisAttitudeDataCountParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
