// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package unifieddatalibrary_test

import (
	"context"
	"errors"
	"os"
	"testing"
	"time"

	"github.com/stainless-sdks/unifieddatalibrary-go"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/testutil"
	"github.com/stainless-sdks/unifieddatalibrary-go/option"
)

func TestManeuverNewWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	err := client.Maneuvers.New(context.TODO(), unifieddatalibrary.ManeuverNewParams{
		ClassificationMarking: "U",
		DataMode:              unifieddatalibrary.ManeuverNewParamsDataModeTest,
		EventStartTime:        time.Now(),
		Source:                "Bluestaq",
		ID:                    unifieddatalibrary.String("MANEUVER-ID"),
		Algorithm:             unifieddatalibrary.String("Example algorithm"),
		Characterization:      unifieddatalibrary.String("North-South Station Keeping"),
		CharacterizationUnc:   unifieddatalibrary.Float(0.15),
		Cov:                   []float64{1.1, 2.4, 3.4, 4.1, 5.6, 6.2, 7.9, 8, 9.2, 10.1},
		DeltaMass:             unifieddatalibrary.Float(0.15),
		DeltaPos:              unifieddatalibrary.Float(0.715998327),
		DeltaPosU:             unifieddatalibrary.Float(-0.022172844),
		DeltaPosV:             unifieddatalibrary.Float(-0.033700154),
		DeltaPosW:             unifieddatalibrary.Float(-0.714861014),
		DeltaVel:              unifieddatalibrary.Float(0.000631505),
		DeltaVelU:             unifieddatalibrary.Float(0.0000350165629389647),
		DeltaVelV:             unifieddatalibrary.Float(0.000544413),
		DeltaVelW:             unifieddatalibrary.Float(-0.000318099),
		Description:           unifieddatalibrary.String("Example notes"),
		Descriptor:            unifieddatalibrary.String("Example descriptor"),
		EventEndTime:          unifieddatalibrary.Time(time.Now()),
		EventID:               unifieddatalibrary.String("EVENT-ID"),
		IDSensor:              unifieddatalibrary.String("SENSOR-ID"),
		ManeuverUnc:           unifieddatalibrary.Float(0.5),
		MnvrAccels:            []float64{0.05, 0.1, 0.05},
		MnvrAccelTimes:        []float64{10.25, 50.56, 150.78},
		MnvrAccelUncs:         []float64{0.0005, 0.001, 0.0005},
		NumAccelPoints:        unifieddatalibrary.Int(3),
		NumObs:                unifieddatalibrary.Int(10),
		OdFitEndTime:          unifieddatalibrary.Time(time.Now()),
		Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
		OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
		OrigSensorID:          unifieddatalibrary.String("ORIGSENSOR-ID"),
		PostApogee:            unifieddatalibrary.Float(35800.1),
		PostArea:              unifieddatalibrary.Float(35.77),
		PostBallisticCoeff:    unifieddatalibrary.Float(0.000433209),
		PostDriftRate:         unifieddatalibrary.Float(-0.0125),
		PostEccentricity:      unifieddatalibrary.Float(0.000164),
		PostEventElset: unifieddatalibrary.ManeuverNewParamsPostEventElset{
			ClassificationMarking: "U",
			DataMode:              "TEST",
			Epoch:                 time.Now(),
			Source:                "Bluestaq",
			Agom:                  unifieddatalibrary.Float(0.0126),
			Algorithm:             unifieddatalibrary.String("Example algorithm"),
			Apogee:                unifieddatalibrary.Float(1.1),
			ArgOfPerigee:          unifieddatalibrary.Float(1.1),
			BallisticCoeff:        unifieddatalibrary.Float(0.00815),
			BStar:                 unifieddatalibrary.Float(1.1),
			Descriptor:            unifieddatalibrary.String("Example description"),
			Eccentricity:          unifieddatalibrary.Float(0.333),
			EphemType:             unifieddatalibrary.Int(1),
			IDElset:               unifieddatalibrary.String("ELSET-ID"),
			IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
			Inclination:           unifieddatalibrary.Float(45.1),
			MeanAnomaly:           unifieddatalibrary.Float(179.1),
			MeanMotion:            unifieddatalibrary.Float(1.1),
			MeanMotionDDot:        unifieddatalibrary.Float(1.1),
			MeanMotionDot:         unifieddatalibrary.Float(1.1),
			Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
			OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
			Perigee:               unifieddatalibrary.Float(1.1),
			Period:                unifieddatalibrary.Float(1.1),
			Raan:                  unifieddatalibrary.Float(1.1),
			RawFileUri:            unifieddatalibrary.String("Example URI"),
			RevNo:                 unifieddatalibrary.Int(111),
			SatNo:                 unifieddatalibrary.Int(12),
			SemiMajorAxis:         unifieddatalibrary.Float(1.1),
			SourcedData:           []string{"OBSERVATION_UUID1", "OBSERVATION_UUID2"},
			SourcedDataTypes:      []string{"RADAR", "RF"},
			Tags:                  []string{"PROVIDER_TAG1", "PROVIDER_TAG2"},
			TransactionID:         unifieddatalibrary.String("TRANSACTION-ID"),
			Uct:                   unifieddatalibrary.Bool(false),
		},
		PostEventIDElset:       unifieddatalibrary.String("225adf4c-8606-40a8-929e-63e22cffe220"),
		PostEventIDStateVector: unifieddatalibrary.String("d83a23f8-1496-485a-bd88-ec5808c73299"),
		PostEventStateVector: unifieddatalibrary.ManeuverNewParamsPostEventStateVector{
			ClassificationMarking: "U",
			DataMode:              "TEST",
			Epoch:                 time.Now(),
			Source:                "Bluestaq",
			ActualOdSpan:          unifieddatalibrary.Float(3.5),
			Algorithm:             unifieddatalibrary.String("SAMPLE_ALGORITHM"),
			Alt1ReferenceFrame:    unifieddatalibrary.String("TEME"),
			Alt2ReferenceFrame:    unifieddatalibrary.String("EFG/TDR"),
			Area:                  unifieddatalibrary.Float(5.065),
			BDot:                  unifieddatalibrary.Float(1.23),
			CmOffset:              unifieddatalibrary.Float(1.23),
			Cov:                   []float64{1.1, 2.4, 3.8, 4.2, 5.5, 6},
			CovMethod:             unifieddatalibrary.String("CALCULATED"),
			CovReferenceFrame:     "J2000",
			Descriptor:            unifieddatalibrary.String("descriptor"),
			DragArea:              unifieddatalibrary.Float(4.739),
			DragCoeff:             unifieddatalibrary.Float(0.0224391269775),
			DragModel:             unifieddatalibrary.String("JAC70"),
			Edr:                   unifieddatalibrary.Float(1.23),
			EqCov:                 []float64{1.1, 2.2},
			ErrorControl:          unifieddatalibrary.Float(1.23),
			FixedStep:             unifieddatalibrary.Bool(true),
			GeopotentialModel:     unifieddatalibrary.String("EGM-96"),
			Iau1980Terms:          unifieddatalibrary.Int(4),
			IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
			IDStateVector:         unifieddatalibrary.String("STATEVECTOR-ID"),
			IntegratorMode:        unifieddatalibrary.String("integratorMode"),
			InTrackThrust:         unifieddatalibrary.Bool(true),
			LastObEnd:             unifieddatalibrary.Time(time.Now()),
			LastObStart:           unifieddatalibrary.Time(time.Now()),
			LeapSecondTime:        unifieddatalibrary.Time(time.Now()),
			LunarSolar:            unifieddatalibrary.Bool(true),
			Mass:                  unifieddatalibrary.Float(164.5),
			ObsAvailable:          unifieddatalibrary.Int(376),
			ObsUsed:               unifieddatalibrary.Int(374),
			Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
			OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
			Partials:              unifieddatalibrary.String("ANALYTIC"),
			Pedigree:              unifieddatalibrary.String("CONJUNCTION"),
			PolarMotionX:          unifieddatalibrary.Float(1.23),
			PolarMotionY:          unifieddatalibrary.Float(1.23),
			PosUnc:                unifieddatalibrary.Float(0.333399744452),
			RawFileUri:            unifieddatalibrary.String("rawFileURI"),
			RecOdSpan:             unifieddatalibrary.Float(3.5),
			ReferenceFrame:        "J2000",
			ResidualsAcc:          unifieddatalibrary.Float(99.5),
			RevNo:                 unifieddatalibrary.Int(7205),
			Rms:                   unifieddatalibrary.Float(0.991),
			SatNo:                 unifieddatalibrary.Int(12),
			SigmaPosUvw:           []float64{1.23, 4.56},
			SigmaVelUvw:           []float64{1.23, 4.56},
			SolarFluxApAvg:        unifieddatalibrary.Float(1.23),
			SolarFluxF10:          unifieddatalibrary.Float(1.23),
			SolarFluxF10Avg:       unifieddatalibrary.Float(1.23),
			SolarRadPress:         unifieddatalibrary.Bool(true),
			SolarRadPressCoeff:    unifieddatalibrary.Float(0.0244394),
			SolidEarthTides:       unifieddatalibrary.Bool(true),
			SourcedData:           []string{"DATA1", "DATA2"},
			SourcedDataTypes:      []string{"RADAR"},
			SrpArea:               unifieddatalibrary.Float(4.311),
			StepMode:              unifieddatalibrary.String("AUTO"),
			StepSize:              unifieddatalibrary.Float(1.23),
			StepSizeSelection:     unifieddatalibrary.String("AUTO"),
			Tags:                  []string{"TAG1", "TAG2"},
			TaiUtc:                unifieddatalibrary.Float(1.23),
			ThrustAccel:           unifieddatalibrary.Float(1.23),
			TracksAvail:           unifieddatalibrary.Int(163),
			TracksUsed:            unifieddatalibrary.Int(163),
			TransactionID:         unifieddatalibrary.String("transactionId"),
			Uct:                   unifieddatalibrary.Bool(true),
			Ut1Rate:               unifieddatalibrary.Float(1.23),
			Ut1Utc:                unifieddatalibrary.Float(1.23),
			VelUnc:                unifieddatalibrary.Float(0.000004),
			Xaccel:                unifieddatalibrary.Float(-2.12621392),
			Xpos:                  unifieddatalibrary.Float(-1118.577381),
			XposAlt1:              unifieddatalibrary.Float(-1145.688502),
			XposAlt2:              unifieddatalibrary.Float(-1456.915926),
			Xvel:                  unifieddatalibrary.Float(-4.25242784),
			XvelAlt1:              unifieddatalibrary.Float(-4.270832252),
			XvelAlt2:              unifieddatalibrary.Float(-1.219814294),
			Yaccel:                unifieddatalibrary.Float(2.645553717),
			Ypos:                  unifieddatalibrary.Float(3026.231084),
			YposAlt1:              unifieddatalibrary.Float(3020.729572),
			YposAlt2:              unifieddatalibrary.Float(-2883.540406),
			Yvel:                  unifieddatalibrary.Float(5.291107434),
			YvelAlt1:              unifieddatalibrary.Float(5.27074276),
			YvelAlt2:              unifieddatalibrary.Float(-6.602080212),
			Zaccel:                unifieddatalibrary.Float(-1.06310696),
			Zpos:                  unifieddatalibrary.Float(6167.831808),
			ZposAlt1:              unifieddatalibrary.Float(6165.55187),
			ZposAlt2:              unifieddatalibrary.Float(6165.55187),
			Zvel:                  unifieddatalibrary.Float(-3.356493869),
			ZvelAlt1:              unifieddatalibrary.Float(-3.365155181),
			ZvelAlt2:              unifieddatalibrary.Float(-3.365155181),
		},
		PostGeoLongitude:        unifieddatalibrary.Float(-93.15),
		PostInclination:         unifieddatalibrary.Float(0.0327),
		PostMass:                unifieddatalibrary.Float(1844.5),
		PostPerigee:             unifieddatalibrary.Float(35787.9),
		PostPeriod:              unifieddatalibrary.Float(1436.01),
		PostPosX:                unifieddatalibrary.Float(3589.351957),
		PostPosY:                unifieddatalibrary.Float(42017.26823),
		PostPosZ:                unifieddatalibrary.Float(-1.27161796),
		PostRaan:                unifieddatalibrary.Float(98.3335),
		PostRadiationPressCoeff: unifieddatalibrary.Float(4.51e-7),
		PostSigmaU:              unifieddatalibrary.Float(12.285),
		PostSigmaV:              unifieddatalibrary.Float(71.339),
		PostSigmaW:              unifieddatalibrary.Float(12.77),
		PostSma:                 unifieddatalibrary.Float(42164.87),
		PostVelX:                unifieddatalibrary.Float(-3.063152826),
		PostVelY:                unifieddatalibrary.Float(0.261586769),
		PostVelZ:                unifieddatalibrary.Float(0.006842148),
		PreApogee:               unifieddatalibrary.Float(35802),
		PreBallisticCoeff:       unifieddatalibrary.Float(0.000437116),
		PreDriftRate:            unifieddatalibrary.Float(-0.0125),
		PreEccentricity:         unifieddatalibrary.Float(0.00017),
		PreEventElset: unifieddatalibrary.ManeuverNewParamsPreEventElset{
			ClassificationMarking: "U",
			DataMode:              "TEST",
			Epoch:                 time.Now(),
			Source:                "Bluestaq",
			Agom:                  unifieddatalibrary.Float(0.0126),
			Algorithm:             unifieddatalibrary.String("Example algorithm"),
			Apogee:                unifieddatalibrary.Float(1.1),
			ArgOfPerigee:          unifieddatalibrary.Float(1.1),
			BallisticCoeff:        unifieddatalibrary.Float(0.00815),
			BStar:                 unifieddatalibrary.Float(1.1),
			Descriptor:            unifieddatalibrary.String("Example description"),
			Eccentricity:          unifieddatalibrary.Float(0.333),
			EphemType:             unifieddatalibrary.Int(1),
			IDElset:               unifieddatalibrary.String("ELSET-ID"),
			IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
			Inclination:           unifieddatalibrary.Float(45.1),
			MeanAnomaly:           unifieddatalibrary.Float(179.1),
			MeanMotion:            unifieddatalibrary.Float(1.1),
			MeanMotionDDot:        unifieddatalibrary.Float(1.1),
			MeanMotionDot:         unifieddatalibrary.Float(1.1),
			Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
			OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
			Perigee:               unifieddatalibrary.Float(1.1),
			Period:                unifieddatalibrary.Float(1.1),
			Raan:                  unifieddatalibrary.Float(1.1),
			RawFileUri:            unifieddatalibrary.String("Example URI"),
			RevNo:                 unifieddatalibrary.Int(111),
			SatNo:                 unifieddatalibrary.Int(12),
			SemiMajorAxis:         unifieddatalibrary.Float(1.1),
			SourcedData:           []string{"OBSERVATION_UUID1", "OBSERVATION_UUID2"},
			SourcedDataTypes:      []string{"RADAR", "RF"},
			Tags:                  []string{"PROVIDER_TAG1", "PROVIDER_TAG2"},
			TransactionID:         unifieddatalibrary.String("TRANSACTION-ID"),
			Uct:                   unifieddatalibrary.Bool(false),
		},
		PreEventIDElset:       unifieddatalibrary.String("80e544b7-6a17-4554-8abf-7301e98f8e5d"),
		PreEventIDStateVector: unifieddatalibrary.String("6e291992-8ae3-4592-bb0f-055715bf4803"),
		PreEventStateVector: unifieddatalibrary.ManeuverNewParamsPreEventStateVector{
			ClassificationMarking: "U",
			DataMode:              "TEST",
			Epoch:                 time.Now(),
			Source:                "Bluestaq",
			ActualOdSpan:          unifieddatalibrary.Float(3.5),
			Algorithm:             unifieddatalibrary.String("SAMPLE_ALGORITHM"),
			Alt1ReferenceFrame:    unifieddatalibrary.String("TEME"),
			Alt2ReferenceFrame:    unifieddatalibrary.String("EFG/TDR"),
			Area:                  unifieddatalibrary.Float(5.065),
			BDot:                  unifieddatalibrary.Float(1.23),
			CmOffset:              unifieddatalibrary.Float(1.23),
			Cov:                   []float64{1.1, 2.4, 3.8, 4.2, 5.5, 6},
			CovMethod:             unifieddatalibrary.String("CALCULATED"),
			CovReferenceFrame:     "J2000",
			Descriptor:            unifieddatalibrary.String("descriptor"),
			DragArea:              unifieddatalibrary.Float(4.739),
			DragCoeff:             unifieddatalibrary.Float(0.0224391269775),
			DragModel:             unifieddatalibrary.String("JAC70"),
			Edr:                   unifieddatalibrary.Float(1.23),
			EqCov:                 []float64{1.1, 2.2},
			ErrorControl:          unifieddatalibrary.Float(1.23),
			FixedStep:             unifieddatalibrary.Bool(true),
			GeopotentialModel:     unifieddatalibrary.String("EGM-96"),
			Iau1980Terms:          unifieddatalibrary.Int(4),
			IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
			IDStateVector:         unifieddatalibrary.String("STATEVECTOR-ID"),
			IntegratorMode:        unifieddatalibrary.String("integratorMode"),
			InTrackThrust:         unifieddatalibrary.Bool(true),
			LastObEnd:             unifieddatalibrary.Time(time.Now()),
			LastObStart:           unifieddatalibrary.Time(time.Now()),
			LeapSecondTime:        unifieddatalibrary.Time(time.Now()),
			LunarSolar:            unifieddatalibrary.Bool(true),
			Mass:                  unifieddatalibrary.Float(164.5),
			ObsAvailable:          unifieddatalibrary.Int(376),
			ObsUsed:               unifieddatalibrary.Int(374),
			Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
			OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
			Partials:              unifieddatalibrary.String("ANALYTIC"),
			Pedigree:              unifieddatalibrary.String("CONJUNCTION"),
			PolarMotionX:          unifieddatalibrary.Float(1.23),
			PolarMotionY:          unifieddatalibrary.Float(1.23),
			PosUnc:                unifieddatalibrary.Float(0.333399744452),
			RawFileUri:            unifieddatalibrary.String("rawFileURI"),
			RecOdSpan:             unifieddatalibrary.Float(3.5),
			ReferenceFrame:        "J2000",
			ResidualsAcc:          unifieddatalibrary.Float(99.5),
			RevNo:                 unifieddatalibrary.Int(7205),
			Rms:                   unifieddatalibrary.Float(0.991),
			SatNo:                 unifieddatalibrary.Int(12),
			SigmaPosUvw:           []float64{1.23, 4.56},
			SigmaVelUvw:           []float64{1.23, 4.56},
			SolarFluxApAvg:        unifieddatalibrary.Float(1.23),
			SolarFluxF10:          unifieddatalibrary.Float(1.23),
			SolarFluxF10Avg:       unifieddatalibrary.Float(1.23),
			SolarRadPress:         unifieddatalibrary.Bool(true),
			SolarRadPressCoeff:    unifieddatalibrary.Float(0.0244394),
			SolidEarthTides:       unifieddatalibrary.Bool(true),
			SourcedData:           []string{"DATA1", "DATA2"},
			SourcedDataTypes:      []string{"RADAR"},
			SrpArea:               unifieddatalibrary.Float(4.311),
			StepMode:              unifieddatalibrary.String("AUTO"),
			StepSize:              unifieddatalibrary.Float(1.23),
			StepSizeSelection:     unifieddatalibrary.String("AUTO"),
			Tags:                  []string{"TAG1", "TAG2"},
			TaiUtc:                unifieddatalibrary.Float(1.23),
			ThrustAccel:           unifieddatalibrary.Float(1.23),
			TracksAvail:           unifieddatalibrary.Int(163),
			TracksUsed:            unifieddatalibrary.Int(163),
			TransactionID:         unifieddatalibrary.String("transactionId"),
			Uct:                   unifieddatalibrary.Bool(true),
			Ut1Rate:               unifieddatalibrary.Float(1.23),
			Ut1Utc:                unifieddatalibrary.Float(1.23),
			VelUnc:                unifieddatalibrary.Float(0.000004),
			Xaccel:                unifieddatalibrary.Float(-2.12621392),
			Xpos:                  unifieddatalibrary.Float(-1118.577381),
			XposAlt1:              unifieddatalibrary.Float(-1145.688502),
			XposAlt2:              unifieddatalibrary.Float(-1456.915926),
			Xvel:                  unifieddatalibrary.Float(-4.25242784),
			XvelAlt1:              unifieddatalibrary.Float(-4.270832252),
			XvelAlt2:              unifieddatalibrary.Float(-1.219814294),
			Yaccel:                unifieddatalibrary.Float(2.645553717),
			Ypos:                  unifieddatalibrary.Float(3026.231084),
			YposAlt1:              unifieddatalibrary.Float(3020.729572),
			YposAlt2:              unifieddatalibrary.Float(-2883.540406),
			Yvel:                  unifieddatalibrary.Float(5.291107434),
			YvelAlt1:              unifieddatalibrary.Float(5.27074276),
			YvelAlt2:              unifieddatalibrary.Float(-6.602080212),
			Zaccel:                unifieddatalibrary.Float(-1.06310696),
			Zpos:                  unifieddatalibrary.Float(6167.831808),
			ZposAlt1:              unifieddatalibrary.Float(6165.55187),
			ZposAlt2:              unifieddatalibrary.Float(6165.55187),
			Zvel:                  unifieddatalibrary.Float(-3.356493869),
			ZvelAlt1:              unifieddatalibrary.Float(-3.365155181),
			ZvelAlt2:              unifieddatalibrary.Float(-3.365155181),
		},
		PreGeoLongitude:        unifieddatalibrary.Float(-93.12),
		PreInclination:         unifieddatalibrary.Float(0.0336),
		PrePerigee:             unifieddatalibrary.Float(35786.5),
		PrePeriod:              unifieddatalibrary.Float(1436.12),
		PrePosX:                unifieddatalibrary.Float(3584.432545),
		PrePosY:                unifieddatalibrary.Float(42028.43245),
		PrePosZ:                unifieddatalibrary.Float(-1.97765),
		PreRaan:                unifieddatalibrary.Float(98.3336),
		PreRadiationPressCoeff: unifieddatalibrary.Float(4.51e-7),
		PreSigmaU:              unifieddatalibrary.Float(0.215),
		PreSigmaV:              unifieddatalibrary.Float(1.97),
		PreSigmaW:              unifieddatalibrary.Float(0.208),
		PreSma:                 unifieddatalibrary.Float(42165.1),
		PreVelX:                unifieddatalibrary.Float(-2.543266),
		PreVelY:                unifieddatalibrary.Float(0.24876),
		PreVelZ:                unifieddatalibrary.Float(0.0067352),
		ReportTime:             unifieddatalibrary.Time(time.Now()),
		SatNo:                  unifieddatalibrary.Int(12),
		SourcedData:            []string{"SOURCEDDATA-ID", "SOURCEDDATA-ID"},
		SourcedDataTypes:       []string{"EO", "RADAR"},
		StateModel:             unifieddatalibrary.String("Example name"),
		StateModelVersion:      unifieddatalibrary.Float(3),
		Status:                 unifieddatalibrary.String("POSSIBLE"),
		Tags:                   []string{"PROVIDER_TAG1", "PROVIDERTAG2"},
		TotalBurnTime:          unifieddatalibrary.Float(600.72),
		TransactionID:          unifieddatalibrary.String("TRANSACTION-ID"),
		Uct:                    unifieddatalibrary.Bool(false),
	})
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverListWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	_, err := client.Maneuvers.List(context.TODO(), unifieddatalibrary.ManeuverListParams{
		EventStartTime: time.Now(),
		FirstResult:    unifieddatalibrary.Int(0),
		MaxResults:     unifieddatalibrary.Int(0),
	})
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverCountWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	_, err := client.Maneuvers.Count(context.TODO(), unifieddatalibrary.ManeuverCountParams{
		EventStartTime: time.Now(),
		FirstResult:    unifieddatalibrary.Int(0),
		MaxResults:     unifieddatalibrary.Int(0),
	})
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverNewBulk(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	err := client.Maneuvers.NewBulk(context.TODO(), unifieddatalibrary.ManeuverNewBulkParams{
		Body: []unifieddatalibrary.ManeuverNewBulkParamsBody{{
			ClassificationMarking: "U",
			DataMode:              "TEST",
			EventStartTime:        time.Now(),
			Source:                "Bluestaq",
			ID:                    unifieddatalibrary.String("MANEUVER-ID"),
			Algorithm:             unifieddatalibrary.String("Example algorithm"),
			Characterization:      unifieddatalibrary.String("North-South Station Keeping"),
			CharacterizationUnc:   unifieddatalibrary.Float(0.15),
			Cov:                   []float64{1.1, 2.4, 3.4, 4.1, 5.6, 6.2, 7.9, 8, 9.2, 10.1},
			DeltaMass:             unifieddatalibrary.Float(0.15),
			DeltaPos:              unifieddatalibrary.Float(0.715998327),
			DeltaPosU:             unifieddatalibrary.Float(-0.022172844),
			DeltaPosV:             unifieddatalibrary.Float(-0.033700154),
			DeltaPosW:             unifieddatalibrary.Float(-0.714861014),
			DeltaVel:              unifieddatalibrary.Float(0.000631505),
			DeltaVelU:             unifieddatalibrary.Float(0.0000350165629389647),
			DeltaVelV:             unifieddatalibrary.Float(0.000544413),
			DeltaVelW:             unifieddatalibrary.Float(-0.000318099),
			Description:           unifieddatalibrary.String("Example notes"),
			Descriptor:            unifieddatalibrary.String("Example descriptor"),
			EventEndTime:          unifieddatalibrary.Time(time.Now()),
			EventID:               unifieddatalibrary.String("EVENT-ID"),
			IDSensor:              unifieddatalibrary.String("SENSOR-ID"),
			ManeuverUnc:           unifieddatalibrary.Float(0.5),
			MnvrAccels:            []float64{0.05, 0.1, 0.05},
			MnvrAccelTimes:        []float64{10.25, 50.56, 150.78},
			MnvrAccelUncs:         []float64{0.0005, 0.001, 0.0005},
			NumAccelPoints:        unifieddatalibrary.Int(3),
			NumObs:                unifieddatalibrary.Int(10),
			OdFitEndTime:          unifieddatalibrary.Time(time.Now()),
			Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
			OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
			OrigSensorID:          unifieddatalibrary.String("ORIGSENSOR-ID"),
			PostApogee:            unifieddatalibrary.Float(35800.1),
			PostArea:              unifieddatalibrary.Float(35.77),
			PostBallisticCoeff:    unifieddatalibrary.Float(0.000433209),
			PostDriftRate:         unifieddatalibrary.Float(-0.0125),
			PostEccentricity:      unifieddatalibrary.Float(0.000164),
			PostEventElset: unifieddatalibrary.ManeuverNewBulkParamsBodyPostEventElset{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				Agom:                  unifieddatalibrary.Float(0.0126),
				Algorithm:             unifieddatalibrary.String("Example algorithm"),
				Apogee:                unifieddatalibrary.Float(1.1),
				ArgOfPerigee:          unifieddatalibrary.Float(1.1),
				BallisticCoeff:        unifieddatalibrary.Float(0.00815),
				BStar:                 unifieddatalibrary.Float(1.1),
				Descriptor:            unifieddatalibrary.String("Example description"),
				Eccentricity:          unifieddatalibrary.Float(0.333),
				EphemType:             unifieddatalibrary.Int(1),
				IDElset:               unifieddatalibrary.String("ELSET-ID"),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				Inclination:           unifieddatalibrary.Float(45.1),
				MeanAnomaly:           unifieddatalibrary.Float(179.1),
				MeanMotion:            unifieddatalibrary.Float(1.1),
				MeanMotionDDot:        unifieddatalibrary.Float(1.1),
				MeanMotionDot:         unifieddatalibrary.Float(1.1),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Perigee:               unifieddatalibrary.Float(1.1),
				Period:                unifieddatalibrary.Float(1.1),
				Raan:                  unifieddatalibrary.Float(1.1),
				RawFileUri:            unifieddatalibrary.String("Example URI"),
				RevNo:                 unifieddatalibrary.Int(111),
				SatNo:                 unifieddatalibrary.Int(12),
				SemiMajorAxis:         unifieddatalibrary.Float(1.1),
				SourcedData:           []string{"OBSERVATION_UUID1", "OBSERVATION_UUID2"},
				SourcedDataTypes:      []string{"RADAR", "RF"},
				Tags:                  []string{"PROVIDER_TAG1", "PROVIDER_TAG2"},
				TransactionID:         unifieddatalibrary.String("TRANSACTION-ID"),
				Uct:                   unifieddatalibrary.Bool(false),
			},
			PostEventIDElset:       unifieddatalibrary.String("225adf4c-8606-40a8-929e-63e22cffe220"),
			PostEventIDStateVector: unifieddatalibrary.String("d83a23f8-1496-485a-bd88-ec5808c73299"),
			PostEventStateVector: unifieddatalibrary.ManeuverNewBulkParamsBodyPostEventStateVector{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				ActualOdSpan:          unifieddatalibrary.Float(3.5),
				Algorithm:             unifieddatalibrary.String("SAMPLE_ALGORITHM"),
				Alt1ReferenceFrame:    unifieddatalibrary.String("TEME"),
				Alt2ReferenceFrame:    unifieddatalibrary.String("EFG/TDR"),
				Area:                  unifieddatalibrary.Float(5.065),
				BDot:                  unifieddatalibrary.Float(1.23),
				CmOffset:              unifieddatalibrary.Float(1.23),
				Cov:                   []float64{1.1, 2.4, 3.8, 4.2, 5.5, 6},
				CovMethod:             unifieddatalibrary.String("CALCULATED"),
				CovReferenceFrame:     "J2000",
				Descriptor:            unifieddatalibrary.String("descriptor"),
				DragArea:              unifieddatalibrary.Float(4.739),
				DragCoeff:             unifieddatalibrary.Float(0.0224391269775),
				DragModel:             unifieddatalibrary.String("JAC70"),
				Edr:                   unifieddatalibrary.Float(1.23),
				EqCov:                 []float64{1.1, 2.2},
				ErrorControl:          unifieddatalibrary.Float(1.23),
				FixedStep:             unifieddatalibrary.Bool(true),
				GeopotentialModel:     unifieddatalibrary.String("EGM-96"),
				Iau1980Terms:          unifieddatalibrary.Int(4),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				IDStateVector:         unifieddatalibrary.String("STATEVECTOR-ID"),
				IntegratorMode:        unifieddatalibrary.String("integratorMode"),
				InTrackThrust:         unifieddatalibrary.Bool(true),
				LastObEnd:             unifieddatalibrary.Time(time.Now()),
				LastObStart:           unifieddatalibrary.Time(time.Now()),
				LeapSecondTime:        unifieddatalibrary.Time(time.Now()),
				LunarSolar:            unifieddatalibrary.Bool(true),
				Mass:                  unifieddatalibrary.Float(164.5),
				ObsAvailable:          unifieddatalibrary.Int(376),
				ObsUsed:               unifieddatalibrary.Int(374),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Partials:              unifieddatalibrary.String("ANALYTIC"),
				Pedigree:              unifieddatalibrary.String("CONJUNCTION"),
				PolarMotionX:          unifieddatalibrary.Float(1.23),
				PolarMotionY:          unifieddatalibrary.Float(1.23),
				PosUnc:                unifieddatalibrary.Float(0.333399744452),
				RawFileUri:            unifieddatalibrary.String("rawFileURI"),
				RecOdSpan:             unifieddatalibrary.Float(3.5),
				ReferenceFrame:        "J2000",
				ResidualsAcc:          unifieddatalibrary.Float(99.5),
				RevNo:                 unifieddatalibrary.Int(7205),
				Rms:                   unifieddatalibrary.Float(0.991),
				SatNo:                 unifieddatalibrary.Int(12),
				SigmaPosUvw:           []float64{1.23, 4.56},
				SigmaVelUvw:           []float64{1.23, 4.56},
				SolarFluxApAvg:        unifieddatalibrary.Float(1.23),
				SolarFluxF10:          unifieddatalibrary.Float(1.23),
				SolarFluxF10Avg:       unifieddatalibrary.Float(1.23),
				SolarRadPress:         unifieddatalibrary.Bool(true),
				SolarRadPressCoeff:    unifieddatalibrary.Float(0.0244394),
				SolidEarthTides:       unifieddatalibrary.Bool(true),
				SourcedData:           []string{"DATA1", "DATA2"},
				SourcedDataTypes:      []string{"RADAR"},
				SrpArea:               unifieddatalibrary.Float(4.311),
				StepMode:              unifieddatalibrary.String("AUTO"),
				StepSize:              unifieddatalibrary.Float(1.23),
				StepSizeSelection:     unifieddatalibrary.String("AUTO"),
				Tags:                  []string{"TAG1", "TAG2"},
				TaiUtc:                unifieddatalibrary.Float(1.23),
				ThrustAccel:           unifieddatalibrary.Float(1.23),
				TracksAvail:           unifieddatalibrary.Int(163),
				TracksUsed:            unifieddatalibrary.Int(163),
				TransactionID:         unifieddatalibrary.String("transactionId"),
				Uct:                   unifieddatalibrary.Bool(true),
				Ut1Rate:               unifieddatalibrary.Float(1.23),
				Ut1Utc:                unifieddatalibrary.Float(1.23),
				VelUnc:                unifieddatalibrary.Float(0.000004),
				Xaccel:                unifieddatalibrary.Float(-2.12621392),
				Xpos:                  unifieddatalibrary.Float(-1118.577381),
				XposAlt1:              unifieddatalibrary.Float(-1145.688502),
				XposAlt2:              unifieddatalibrary.Float(-1456.915926),
				Xvel:                  unifieddatalibrary.Float(-4.25242784),
				XvelAlt1:              unifieddatalibrary.Float(-4.270832252),
				XvelAlt2:              unifieddatalibrary.Float(-1.219814294),
				Yaccel:                unifieddatalibrary.Float(2.645553717),
				Ypos:                  unifieddatalibrary.Float(3026.231084),
				YposAlt1:              unifieddatalibrary.Float(3020.729572),
				YposAlt2:              unifieddatalibrary.Float(-2883.540406),
				Yvel:                  unifieddatalibrary.Float(5.291107434),
				YvelAlt1:              unifieddatalibrary.Float(5.27074276),
				YvelAlt2:              unifieddatalibrary.Float(-6.602080212),
				Zaccel:                unifieddatalibrary.Float(-1.06310696),
				Zpos:                  unifieddatalibrary.Float(6167.831808),
				ZposAlt1:              unifieddatalibrary.Float(6165.55187),
				ZposAlt2:              unifieddatalibrary.Float(6165.55187),
				Zvel:                  unifieddatalibrary.Float(-3.356493869),
				ZvelAlt1:              unifieddatalibrary.Float(-3.365155181),
				ZvelAlt2:              unifieddatalibrary.Float(-3.365155181),
			},
			PostGeoLongitude:        unifieddatalibrary.Float(-93.15),
			PostInclination:         unifieddatalibrary.Float(0.0327),
			PostMass:                unifieddatalibrary.Float(1844.5),
			PostPerigee:             unifieddatalibrary.Float(35787.9),
			PostPeriod:              unifieddatalibrary.Float(1436.01),
			PostPosX:                unifieddatalibrary.Float(3589.351957),
			PostPosY:                unifieddatalibrary.Float(42017.26823),
			PostPosZ:                unifieddatalibrary.Float(-1.27161796),
			PostRaan:                unifieddatalibrary.Float(98.3335),
			PostRadiationPressCoeff: unifieddatalibrary.Float(4.51e-7),
			PostSigmaU:              unifieddatalibrary.Float(12.285),
			PostSigmaV:              unifieddatalibrary.Float(71.339),
			PostSigmaW:              unifieddatalibrary.Float(12.77),
			PostSma:                 unifieddatalibrary.Float(42164.87),
			PostVelX:                unifieddatalibrary.Float(-3.063152826),
			PostVelY:                unifieddatalibrary.Float(0.261586769),
			PostVelZ:                unifieddatalibrary.Float(0.006842148),
			PreApogee:               unifieddatalibrary.Float(35802),
			PreBallisticCoeff:       unifieddatalibrary.Float(0.000437116),
			PreDriftRate:            unifieddatalibrary.Float(-0.0125),
			PreEccentricity:         unifieddatalibrary.Float(0.00017),
			PreEventElset: unifieddatalibrary.ManeuverNewBulkParamsBodyPreEventElset{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				Agom:                  unifieddatalibrary.Float(0.0126),
				Algorithm:             unifieddatalibrary.String("Example algorithm"),
				Apogee:                unifieddatalibrary.Float(1.1),
				ArgOfPerigee:          unifieddatalibrary.Float(1.1),
				BallisticCoeff:        unifieddatalibrary.Float(0.00815),
				BStar:                 unifieddatalibrary.Float(1.1),
				Descriptor:            unifieddatalibrary.String("Example description"),
				Eccentricity:          unifieddatalibrary.Float(0.333),
				EphemType:             unifieddatalibrary.Int(1),
				IDElset:               unifieddatalibrary.String("ELSET-ID"),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				Inclination:           unifieddatalibrary.Float(45.1),
				MeanAnomaly:           unifieddatalibrary.Float(179.1),
				MeanMotion:            unifieddatalibrary.Float(1.1),
				MeanMotionDDot:        unifieddatalibrary.Float(1.1),
				MeanMotionDot:         unifieddatalibrary.Float(1.1),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Perigee:               unifieddatalibrary.Float(1.1),
				Period:                unifieddatalibrary.Float(1.1),
				Raan:                  unifieddatalibrary.Float(1.1),
				RawFileUri:            unifieddatalibrary.String("Example URI"),
				RevNo:                 unifieddatalibrary.Int(111),
				SatNo:                 unifieddatalibrary.Int(12),
				SemiMajorAxis:         unifieddatalibrary.Float(1.1),
				SourcedData:           []string{"OBSERVATION_UUID1", "OBSERVATION_UUID2"},
				SourcedDataTypes:      []string{"RADAR", "RF"},
				Tags:                  []string{"PROVIDER_TAG1", "PROVIDER_TAG2"},
				TransactionID:         unifieddatalibrary.String("TRANSACTION-ID"),
				Uct:                   unifieddatalibrary.Bool(false),
			},
			PreEventIDElset:       unifieddatalibrary.String("80e544b7-6a17-4554-8abf-7301e98f8e5d"),
			PreEventIDStateVector: unifieddatalibrary.String("6e291992-8ae3-4592-bb0f-055715bf4803"),
			PreEventStateVector: unifieddatalibrary.ManeuverNewBulkParamsBodyPreEventStateVector{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				ActualOdSpan:          unifieddatalibrary.Float(3.5),
				Algorithm:             unifieddatalibrary.String("SAMPLE_ALGORITHM"),
				Alt1ReferenceFrame:    unifieddatalibrary.String("TEME"),
				Alt2ReferenceFrame:    unifieddatalibrary.String("EFG/TDR"),
				Area:                  unifieddatalibrary.Float(5.065),
				BDot:                  unifieddatalibrary.Float(1.23),
				CmOffset:              unifieddatalibrary.Float(1.23),
				Cov:                   []float64{1.1, 2.4, 3.8, 4.2, 5.5, 6},
				CovMethod:             unifieddatalibrary.String("CALCULATED"),
				CovReferenceFrame:     "J2000",
				Descriptor:            unifieddatalibrary.String("descriptor"),
				DragArea:              unifieddatalibrary.Float(4.739),
				DragCoeff:             unifieddatalibrary.Float(0.0224391269775),
				DragModel:             unifieddatalibrary.String("JAC70"),
				Edr:                   unifieddatalibrary.Float(1.23),
				EqCov:                 []float64{1.1, 2.2},
				ErrorControl:          unifieddatalibrary.Float(1.23),
				FixedStep:             unifieddatalibrary.Bool(true),
				GeopotentialModel:     unifieddatalibrary.String("EGM-96"),
				Iau1980Terms:          unifieddatalibrary.Int(4),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				IDStateVector:         unifieddatalibrary.String("STATEVECTOR-ID"),
				IntegratorMode:        unifieddatalibrary.String("integratorMode"),
				InTrackThrust:         unifieddatalibrary.Bool(true),
				LastObEnd:             unifieddatalibrary.Time(time.Now()),
				LastObStart:           unifieddatalibrary.Time(time.Now()),
				LeapSecondTime:        unifieddatalibrary.Time(time.Now()),
				LunarSolar:            unifieddatalibrary.Bool(true),
				Mass:                  unifieddatalibrary.Float(164.5),
				ObsAvailable:          unifieddatalibrary.Int(376),
				ObsUsed:               unifieddatalibrary.Int(374),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Partials:              unifieddatalibrary.String("ANALYTIC"),
				Pedigree:              unifieddatalibrary.String("CONJUNCTION"),
				PolarMotionX:          unifieddatalibrary.Float(1.23),
				PolarMotionY:          unifieddatalibrary.Float(1.23),
				PosUnc:                unifieddatalibrary.Float(0.333399744452),
				RawFileUri:            unifieddatalibrary.String("rawFileURI"),
				RecOdSpan:             unifieddatalibrary.Float(3.5),
				ReferenceFrame:        "J2000",
				ResidualsAcc:          unifieddatalibrary.Float(99.5),
				RevNo:                 unifieddatalibrary.Int(7205),
				Rms:                   unifieddatalibrary.Float(0.991),
				SatNo:                 unifieddatalibrary.Int(12),
				SigmaPosUvw:           []float64{1.23, 4.56},
				SigmaVelUvw:           []float64{1.23, 4.56},
				SolarFluxApAvg:        unifieddatalibrary.Float(1.23),
				SolarFluxF10:          unifieddatalibrary.Float(1.23),
				SolarFluxF10Avg:       unifieddatalibrary.Float(1.23),
				SolarRadPress:         unifieddatalibrary.Bool(true),
				SolarRadPressCoeff:    unifieddatalibrary.Float(0.0244394),
				SolidEarthTides:       unifieddatalibrary.Bool(true),
				SourcedData:           []string{"DATA1", "DATA2"},
				SourcedDataTypes:      []string{"RADAR"},
				SrpArea:               unifieddatalibrary.Float(4.311),
				StepMode:              unifieddatalibrary.String("AUTO"),
				StepSize:              unifieddatalibrary.Float(1.23),
				StepSizeSelection:     unifieddatalibrary.String("AUTO"),
				Tags:                  []string{"TAG1", "TAG2"},
				TaiUtc:                unifieddatalibrary.Float(1.23),
				ThrustAccel:           unifieddatalibrary.Float(1.23),
				TracksAvail:           unifieddatalibrary.Int(163),
				TracksUsed:            unifieddatalibrary.Int(163),
				TransactionID:         unifieddatalibrary.String("transactionId"),
				Uct:                   unifieddatalibrary.Bool(true),
				Ut1Rate:               unifieddatalibrary.Float(1.23),
				Ut1Utc:                unifieddatalibrary.Float(1.23),
				VelUnc:                unifieddatalibrary.Float(0.000004),
				Xaccel:                unifieddatalibrary.Float(-2.12621392),
				Xpos:                  unifieddatalibrary.Float(-1118.577381),
				XposAlt1:              unifieddatalibrary.Float(-1145.688502),
				XposAlt2:              unifieddatalibrary.Float(-1456.915926),
				Xvel:                  unifieddatalibrary.Float(-4.25242784),
				XvelAlt1:              unifieddatalibrary.Float(-4.270832252),
				XvelAlt2:              unifieddatalibrary.Float(-1.219814294),
				Yaccel:                unifieddatalibrary.Float(2.645553717),
				Ypos:                  unifieddatalibrary.Float(3026.231084),
				YposAlt1:              unifieddatalibrary.Float(3020.729572),
				YposAlt2:              unifieddatalibrary.Float(-2883.540406),
				Yvel:                  unifieddatalibrary.Float(5.291107434),
				YvelAlt1:              unifieddatalibrary.Float(5.27074276),
				YvelAlt2:              unifieddatalibrary.Float(-6.602080212),
				Zaccel:                unifieddatalibrary.Float(-1.06310696),
				Zpos:                  unifieddatalibrary.Float(6167.831808),
				ZposAlt1:              unifieddatalibrary.Float(6165.55187),
				ZposAlt2:              unifieddatalibrary.Float(6165.55187),
				Zvel:                  unifieddatalibrary.Float(-3.356493869),
				ZvelAlt1:              unifieddatalibrary.Float(-3.365155181),
				ZvelAlt2:              unifieddatalibrary.Float(-3.365155181),
			},
			PreGeoLongitude:        unifieddatalibrary.Float(-93.12),
			PreInclination:         unifieddatalibrary.Float(0.0336),
			PrePerigee:             unifieddatalibrary.Float(35786.5),
			PrePeriod:              unifieddatalibrary.Float(1436.12),
			PrePosX:                unifieddatalibrary.Float(3584.432545),
			PrePosY:                unifieddatalibrary.Float(42028.43245),
			PrePosZ:                unifieddatalibrary.Float(-1.97765),
			PreRaan:                unifieddatalibrary.Float(98.3336),
			PreRadiationPressCoeff: unifieddatalibrary.Float(4.51e-7),
			PreSigmaU:              unifieddatalibrary.Float(0.215),
			PreSigmaV:              unifieddatalibrary.Float(1.97),
			PreSigmaW:              unifieddatalibrary.Float(0.208),
			PreSma:                 unifieddatalibrary.Float(42165.1),
			PreVelX:                unifieddatalibrary.Float(-2.543266),
			PreVelY:                unifieddatalibrary.Float(0.24876),
			PreVelZ:                unifieddatalibrary.Float(0.0067352),
			ReportTime:             unifieddatalibrary.Time(time.Now()),
			SatNo:                  unifieddatalibrary.Int(12),
			SourcedData:            []string{"SOURCEDDATA-ID", "SOURCEDDATA-ID"},
			SourcedDataTypes:       []string{"EO", "RADAR"},
			StateModel:             unifieddatalibrary.String("Example name"),
			StateModelVersion:      unifieddatalibrary.Float(3),
			Status:                 unifieddatalibrary.String("POSSIBLE"),
			Tags:                   []string{"PROVIDER_TAG1", "PROVIDERTAG2"},
			TotalBurnTime:          unifieddatalibrary.Float(600.72),
			TransactionID:          unifieddatalibrary.String("TRANSACTION-ID"),
			Uct:                    unifieddatalibrary.Bool(false),
		}},
	})
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverGetWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	_, err := client.Maneuvers.Get(
		context.TODO(),
		"id",
		unifieddatalibrary.ManeuverGetParams{
			FirstResult: unifieddatalibrary.Int(0),
			MaxResults:  unifieddatalibrary.Int(0),
		},
	)
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverQueryhelp(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	err := client.Maneuvers.Queryhelp(context.TODO())
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverTupleWithOptionalParams(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	_, err := client.Maneuvers.Tuple(context.TODO(), unifieddatalibrary.ManeuverTupleParams{
		Columns:        "columns",
		EventStartTime: time.Now(),
		FirstResult:    unifieddatalibrary.Int(0),
		MaxResults:     unifieddatalibrary.Int(0),
	})
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestManeuverUnvalidatedPublish(t *testing.T) {
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := unifieddatalibrary.NewClient(
		option.WithBaseURL(baseURL),
		option.WithPassword("My Password"),
		option.WithUsername("My Username"),
	)
	err := client.Maneuvers.UnvalidatedPublish(context.TODO(), unifieddatalibrary.ManeuverUnvalidatedPublishParams{
		Body: []unifieddatalibrary.ManeuverUnvalidatedPublishParamsBody{{
			ClassificationMarking: "U",
			DataMode:              "TEST",
			EventStartTime:        time.Now(),
			Source:                "Bluestaq",
			ID:                    unifieddatalibrary.String("MANEUVER-ID"),
			Algorithm:             unifieddatalibrary.String("Example algorithm"),
			Characterization:      unifieddatalibrary.String("North-South Station Keeping"),
			CharacterizationUnc:   unifieddatalibrary.Float(0.15),
			Cov:                   []float64{1.1, 2.4, 3.4, 4.1, 5.6, 6.2, 7.9, 8, 9.2, 10.1},
			DeltaMass:             unifieddatalibrary.Float(0.15),
			DeltaPos:              unifieddatalibrary.Float(0.715998327),
			DeltaPosU:             unifieddatalibrary.Float(-0.022172844),
			DeltaPosV:             unifieddatalibrary.Float(-0.033700154),
			DeltaPosW:             unifieddatalibrary.Float(-0.714861014),
			DeltaVel:              unifieddatalibrary.Float(0.000631505),
			DeltaVelU:             unifieddatalibrary.Float(0.0000350165629389647),
			DeltaVelV:             unifieddatalibrary.Float(0.000544413),
			DeltaVelW:             unifieddatalibrary.Float(-0.000318099),
			Description:           unifieddatalibrary.String("Example notes"),
			Descriptor:            unifieddatalibrary.String("Example descriptor"),
			EventEndTime:          unifieddatalibrary.Time(time.Now()),
			EventID:               unifieddatalibrary.String("EVENT-ID"),
			IDSensor:              unifieddatalibrary.String("SENSOR-ID"),
			ManeuverUnc:           unifieddatalibrary.Float(0.5),
			MnvrAccels:            []float64{0.05, 0.1, 0.05},
			MnvrAccelTimes:        []float64{10.25, 50.56, 150.78},
			MnvrAccelUncs:         []float64{0.0005, 0.001, 0.0005},
			NumAccelPoints:        unifieddatalibrary.Int(3),
			NumObs:                unifieddatalibrary.Int(10),
			OdFitEndTime:          unifieddatalibrary.Time(time.Now()),
			Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
			OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
			OrigSensorID:          unifieddatalibrary.String("ORIGSENSOR-ID"),
			PostApogee:            unifieddatalibrary.Float(35800.1),
			PostArea:              unifieddatalibrary.Float(35.77),
			PostBallisticCoeff:    unifieddatalibrary.Float(0.000433209),
			PostDriftRate:         unifieddatalibrary.Float(-0.0125),
			PostEccentricity:      unifieddatalibrary.Float(0.000164),
			PostEventElset: unifieddatalibrary.ManeuverUnvalidatedPublishParamsBodyPostEventElset{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				Agom:                  unifieddatalibrary.Float(0.0126),
				Algorithm:             unifieddatalibrary.String("Example algorithm"),
				Apogee:                unifieddatalibrary.Float(1.1),
				ArgOfPerigee:          unifieddatalibrary.Float(1.1),
				BallisticCoeff:        unifieddatalibrary.Float(0.00815),
				BStar:                 unifieddatalibrary.Float(1.1),
				Descriptor:            unifieddatalibrary.String("Example description"),
				Eccentricity:          unifieddatalibrary.Float(0.333),
				EphemType:             unifieddatalibrary.Int(1),
				IDElset:               unifieddatalibrary.String("ELSET-ID"),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				Inclination:           unifieddatalibrary.Float(45.1),
				MeanAnomaly:           unifieddatalibrary.Float(179.1),
				MeanMotion:            unifieddatalibrary.Float(1.1),
				MeanMotionDDot:        unifieddatalibrary.Float(1.1),
				MeanMotionDot:         unifieddatalibrary.Float(1.1),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Perigee:               unifieddatalibrary.Float(1.1),
				Period:                unifieddatalibrary.Float(1.1),
				Raan:                  unifieddatalibrary.Float(1.1),
				RawFileUri:            unifieddatalibrary.String("Example URI"),
				RevNo:                 unifieddatalibrary.Int(111),
				SatNo:                 unifieddatalibrary.Int(12),
				SemiMajorAxis:         unifieddatalibrary.Float(1.1),
				SourcedData:           []string{"OBSERVATION_UUID1", "OBSERVATION_UUID2"},
				SourcedDataTypes:      []string{"RADAR", "RF"},
				Tags:                  []string{"PROVIDER_TAG1", "PROVIDER_TAG2"},
				TransactionID:         unifieddatalibrary.String("TRANSACTION-ID"),
				Uct:                   unifieddatalibrary.Bool(false),
			},
			PostEventIDElset:       unifieddatalibrary.String("225adf4c-8606-40a8-929e-63e22cffe220"),
			PostEventIDStateVector: unifieddatalibrary.String("d83a23f8-1496-485a-bd88-ec5808c73299"),
			PostEventStateVector: unifieddatalibrary.ManeuverUnvalidatedPublishParamsBodyPostEventStateVector{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				ActualOdSpan:          unifieddatalibrary.Float(3.5),
				Algorithm:             unifieddatalibrary.String("SAMPLE_ALGORITHM"),
				Alt1ReferenceFrame:    unifieddatalibrary.String("TEME"),
				Alt2ReferenceFrame:    unifieddatalibrary.String("EFG/TDR"),
				Area:                  unifieddatalibrary.Float(5.065),
				BDot:                  unifieddatalibrary.Float(1.23),
				CmOffset:              unifieddatalibrary.Float(1.23),
				Cov:                   []float64{1.1, 2.4, 3.8, 4.2, 5.5, 6},
				CovMethod:             unifieddatalibrary.String("CALCULATED"),
				CovReferenceFrame:     "J2000",
				Descriptor:            unifieddatalibrary.String("descriptor"),
				DragArea:              unifieddatalibrary.Float(4.739),
				DragCoeff:             unifieddatalibrary.Float(0.0224391269775),
				DragModel:             unifieddatalibrary.String("JAC70"),
				Edr:                   unifieddatalibrary.Float(1.23),
				EqCov:                 []float64{1.1, 2.2},
				ErrorControl:          unifieddatalibrary.Float(1.23),
				FixedStep:             unifieddatalibrary.Bool(true),
				GeopotentialModel:     unifieddatalibrary.String("EGM-96"),
				Iau1980Terms:          unifieddatalibrary.Int(4),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				IDStateVector:         unifieddatalibrary.String("STATEVECTOR-ID"),
				IntegratorMode:        unifieddatalibrary.String("integratorMode"),
				InTrackThrust:         unifieddatalibrary.Bool(true),
				LastObEnd:             unifieddatalibrary.Time(time.Now()),
				LastObStart:           unifieddatalibrary.Time(time.Now()),
				LeapSecondTime:        unifieddatalibrary.Time(time.Now()),
				LunarSolar:            unifieddatalibrary.Bool(true),
				Mass:                  unifieddatalibrary.Float(164.5),
				ObsAvailable:          unifieddatalibrary.Int(376),
				ObsUsed:               unifieddatalibrary.Int(374),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Partials:              unifieddatalibrary.String("ANALYTIC"),
				Pedigree:              unifieddatalibrary.String("CONJUNCTION"),
				PolarMotionX:          unifieddatalibrary.Float(1.23),
				PolarMotionY:          unifieddatalibrary.Float(1.23),
				PosUnc:                unifieddatalibrary.Float(0.333399744452),
				RawFileUri:            unifieddatalibrary.String("rawFileURI"),
				RecOdSpan:             unifieddatalibrary.Float(3.5),
				ReferenceFrame:        "J2000",
				ResidualsAcc:          unifieddatalibrary.Float(99.5),
				RevNo:                 unifieddatalibrary.Int(7205),
				Rms:                   unifieddatalibrary.Float(0.991),
				SatNo:                 unifieddatalibrary.Int(12),
				SigmaPosUvw:           []float64{1.23, 4.56},
				SigmaVelUvw:           []float64{1.23, 4.56},
				SolarFluxApAvg:        unifieddatalibrary.Float(1.23),
				SolarFluxF10:          unifieddatalibrary.Float(1.23),
				SolarFluxF10Avg:       unifieddatalibrary.Float(1.23),
				SolarRadPress:         unifieddatalibrary.Bool(true),
				SolarRadPressCoeff:    unifieddatalibrary.Float(0.0244394),
				SolidEarthTides:       unifieddatalibrary.Bool(true),
				SourcedData:           []string{"DATA1", "DATA2"},
				SourcedDataTypes:      []string{"RADAR"},
				SrpArea:               unifieddatalibrary.Float(4.311),
				StepMode:              unifieddatalibrary.String("AUTO"),
				StepSize:              unifieddatalibrary.Float(1.23),
				StepSizeSelection:     unifieddatalibrary.String("AUTO"),
				Tags:                  []string{"TAG1", "TAG2"},
				TaiUtc:                unifieddatalibrary.Float(1.23),
				ThrustAccel:           unifieddatalibrary.Float(1.23),
				TracksAvail:           unifieddatalibrary.Int(163),
				TracksUsed:            unifieddatalibrary.Int(163),
				TransactionID:         unifieddatalibrary.String("transactionId"),
				Uct:                   unifieddatalibrary.Bool(true),
				Ut1Rate:               unifieddatalibrary.Float(1.23),
				Ut1Utc:                unifieddatalibrary.Float(1.23),
				VelUnc:                unifieddatalibrary.Float(0.000004),
				Xaccel:                unifieddatalibrary.Float(-2.12621392),
				Xpos:                  unifieddatalibrary.Float(-1118.577381),
				XposAlt1:              unifieddatalibrary.Float(-1145.688502),
				XposAlt2:              unifieddatalibrary.Float(-1456.915926),
				Xvel:                  unifieddatalibrary.Float(-4.25242784),
				XvelAlt1:              unifieddatalibrary.Float(-4.270832252),
				XvelAlt2:              unifieddatalibrary.Float(-1.219814294),
				Yaccel:                unifieddatalibrary.Float(2.645553717),
				Ypos:                  unifieddatalibrary.Float(3026.231084),
				YposAlt1:              unifieddatalibrary.Float(3020.729572),
				YposAlt2:              unifieddatalibrary.Float(-2883.540406),
				Yvel:                  unifieddatalibrary.Float(5.291107434),
				YvelAlt1:              unifieddatalibrary.Float(5.27074276),
				YvelAlt2:              unifieddatalibrary.Float(-6.602080212),
				Zaccel:                unifieddatalibrary.Float(-1.06310696),
				Zpos:                  unifieddatalibrary.Float(6167.831808),
				ZposAlt1:              unifieddatalibrary.Float(6165.55187),
				ZposAlt2:              unifieddatalibrary.Float(6165.55187),
				Zvel:                  unifieddatalibrary.Float(-3.356493869),
				ZvelAlt1:              unifieddatalibrary.Float(-3.365155181),
				ZvelAlt2:              unifieddatalibrary.Float(-3.365155181),
			},
			PostGeoLongitude:        unifieddatalibrary.Float(-93.15),
			PostInclination:         unifieddatalibrary.Float(0.0327),
			PostMass:                unifieddatalibrary.Float(1844.5),
			PostPerigee:             unifieddatalibrary.Float(35787.9),
			PostPeriod:              unifieddatalibrary.Float(1436.01),
			PostPosX:                unifieddatalibrary.Float(3589.351957),
			PostPosY:                unifieddatalibrary.Float(42017.26823),
			PostPosZ:                unifieddatalibrary.Float(-1.27161796),
			PostRaan:                unifieddatalibrary.Float(98.3335),
			PostRadiationPressCoeff: unifieddatalibrary.Float(4.51e-7),
			PostSigmaU:              unifieddatalibrary.Float(12.285),
			PostSigmaV:              unifieddatalibrary.Float(71.339),
			PostSigmaW:              unifieddatalibrary.Float(12.77),
			PostSma:                 unifieddatalibrary.Float(42164.87),
			PostVelX:                unifieddatalibrary.Float(-3.063152826),
			PostVelY:                unifieddatalibrary.Float(0.261586769),
			PostVelZ:                unifieddatalibrary.Float(0.006842148),
			PreApogee:               unifieddatalibrary.Float(35802),
			PreBallisticCoeff:       unifieddatalibrary.Float(0.000437116),
			PreDriftRate:            unifieddatalibrary.Float(-0.0125),
			PreEccentricity:         unifieddatalibrary.Float(0.00017),
			PreEventElset: unifieddatalibrary.ManeuverUnvalidatedPublishParamsBodyPreEventElset{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				Agom:                  unifieddatalibrary.Float(0.0126),
				Algorithm:             unifieddatalibrary.String("Example algorithm"),
				Apogee:                unifieddatalibrary.Float(1.1),
				ArgOfPerigee:          unifieddatalibrary.Float(1.1),
				BallisticCoeff:        unifieddatalibrary.Float(0.00815),
				BStar:                 unifieddatalibrary.Float(1.1),
				Descriptor:            unifieddatalibrary.String("Example description"),
				Eccentricity:          unifieddatalibrary.Float(0.333),
				EphemType:             unifieddatalibrary.Int(1),
				IDElset:               unifieddatalibrary.String("ELSET-ID"),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				Inclination:           unifieddatalibrary.Float(45.1),
				MeanAnomaly:           unifieddatalibrary.Float(179.1),
				MeanMotion:            unifieddatalibrary.Float(1.1),
				MeanMotionDDot:        unifieddatalibrary.Float(1.1),
				MeanMotionDot:         unifieddatalibrary.Float(1.1),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Perigee:               unifieddatalibrary.Float(1.1),
				Period:                unifieddatalibrary.Float(1.1),
				Raan:                  unifieddatalibrary.Float(1.1),
				RawFileUri:            unifieddatalibrary.String("Example URI"),
				RevNo:                 unifieddatalibrary.Int(111),
				SatNo:                 unifieddatalibrary.Int(12),
				SemiMajorAxis:         unifieddatalibrary.Float(1.1),
				SourcedData:           []string{"OBSERVATION_UUID1", "OBSERVATION_UUID2"},
				SourcedDataTypes:      []string{"RADAR", "RF"},
				Tags:                  []string{"PROVIDER_TAG1", "PROVIDER_TAG2"},
				TransactionID:         unifieddatalibrary.String("TRANSACTION-ID"),
				Uct:                   unifieddatalibrary.Bool(false),
			},
			PreEventIDElset:       unifieddatalibrary.String("80e544b7-6a17-4554-8abf-7301e98f8e5d"),
			PreEventIDStateVector: unifieddatalibrary.String("6e291992-8ae3-4592-bb0f-055715bf4803"),
			PreEventStateVector: unifieddatalibrary.ManeuverUnvalidatedPublishParamsBodyPreEventStateVector{
				ClassificationMarking: "U",
				DataMode:              "TEST",
				Epoch:                 time.Now(),
				Source:                "Bluestaq",
				ActualOdSpan:          unifieddatalibrary.Float(3.5),
				Algorithm:             unifieddatalibrary.String("SAMPLE_ALGORITHM"),
				Alt1ReferenceFrame:    unifieddatalibrary.String("TEME"),
				Alt2ReferenceFrame:    unifieddatalibrary.String("EFG/TDR"),
				Area:                  unifieddatalibrary.Float(5.065),
				BDot:                  unifieddatalibrary.Float(1.23),
				CmOffset:              unifieddatalibrary.Float(1.23),
				Cov:                   []float64{1.1, 2.4, 3.8, 4.2, 5.5, 6},
				CovMethod:             unifieddatalibrary.String("CALCULATED"),
				CovReferenceFrame:     "J2000",
				Descriptor:            unifieddatalibrary.String("descriptor"),
				DragArea:              unifieddatalibrary.Float(4.739),
				DragCoeff:             unifieddatalibrary.Float(0.0224391269775),
				DragModel:             unifieddatalibrary.String("JAC70"),
				Edr:                   unifieddatalibrary.Float(1.23),
				EqCov:                 []float64{1.1, 2.2},
				ErrorControl:          unifieddatalibrary.Float(1.23),
				FixedStep:             unifieddatalibrary.Bool(true),
				GeopotentialModel:     unifieddatalibrary.String("EGM-96"),
				Iau1980Terms:          unifieddatalibrary.Int(4),
				IDOrbitDetermination:  unifieddatalibrary.String("026dd511-8ba5-47d3-9909-836149f87686"),
				IDStateVector:         unifieddatalibrary.String("STATEVECTOR-ID"),
				IntegratorMode:        unifieddatalibrary.String("integratorMode"),
				InTrackThrust:         unifieddatalibrary.Bool(true),
				LastObEnd:             unifieddatalibrary.Time(time.Now()),
				LastObStart:           unifieddatalibrary.Time(time.Now()),
				LeapSecondTime:        unifieddatalibrary.Time(time.Now()),
				LunarSolar:            unifieddatalibrary.Bool(true),
				Mass:                  unifieddatalibrary.Float(164.5),
				ObsAvailable:          unifieddatalibrary.Int(376),
				ObsUsed:               unifieddatalibrary.Int(374),
				Origin:                unifieddatalibrary.String("THIRD_PARTY_DATASOURCE"),
				OrigObjectID:          unifieddatalibrary.String("ORIGOBJECT-ID"),
				Partials:              unifieddatalibrary.String("ANALYTIC"),
				Pedigree:              unifieddatalibrary.String("CONJUNCTION"),
				PolarMotionX:          unifieddatalibrary.Float(1.23),
				PolarMotionY:          unifieddatalibrary.Float(1.23),
				PosUnc:                unifieddatalibrary.Float(0.333399744452),
				RawFileUri:            unifieddatalibrary.String("rawFileURI"),
				RecOdSpan:             unifieddatalibrary.Float(3.5),
				ReferenceFrame:        "J2000",
				ResidualsAcc:          unifieddatalibrary.Float(99.5),
				RevNo:                 unifieddatalibrary.Int(7205),
				Rms:                   unifieddatalibrary.Float(0.991),
				SatNo:                 unifieddatalibrary.Int(12),
				SigmaPosUvw:           []float64{1.23, 4.56},
				SigmaVelUvw:           []float64{1.23, 4.56},
				SolarFluxApAvg:        unifieddatalibrary.Float(1.23),
				SolarFluxF10:          unifieddatalibrary.Float(1.23),
				SolarFluxF10Avg:       unifieddatalibrary.Float(1.23),
				SolarRadPress:         unifieddatalibrary.Bool(true),
				SolarRadPressCoeff:    unifieddatalibrary.Float(0.0244394),
				SolidEarthTides:       unifieddatalibrary.Bool(true),
				SourcedData:           []string{"DATA1", "DATA2"},
				SourcedDataTypes:      []string{"RADAR"},
				SrpArea:               unifieddatalibrary.Float(4.311),
				StepMode:              unifieddatalibrary.String("AUTO"),
				StepSize:              unifieddatalibrary.Float(1.23),
				StepSizeSelection:     unifieddatalibrary.String("AUTO"),
				Tags:                  []string{"TAG1", "TAG2"},
				TaiUtc:                unifieddatalibrary.Float(1.23),
				ThrustAccel:           unifieddatalibrary.Float(1.23),
				TracksAvail:           unifieddatalibrary.Int(163),
				TracksUsed:            unifieddatalibrary.Int(163),
				TransactionID:         unifieddatalibrary.String("transactionId"),
				Uct:                   unifieddatalibrary.Bool(true),
				Ut1Rate:               unifieddatalibrary.Float(1.23),
				Ut1Utc:                unifieddatalibrary.Float(1.23),
				VelUnc:                unifieddatalibrary.Float(0.000004),
				Xaccel:                unifieddatalibrary.Float(-2.12621392),
				Xpos:                  unifieddatalibrary.Float(-1118.577381),
				XposAlt1:              unifieddatalibrary.Float(-1145.688502),
				XposAlt2:              unifieddatalibrary.Float(-1456.915926),
				Xvel:                  unifieddatalibrary.Float(-4.25242784),
				XvelAlt1:              unifieddatalibrary.Float(-4.270832252),
				XvelAlt2:              unifieddatalibrary.Float(-1.219814294),
				Yaccel:                unifieddatalibrary.Float(2.645553717),
				Ypos:                  unifieddatalibrary.Float(3026.231084),
				YposAlt1:              unifieddatalibrary.Float(3020.729572),
				YposAlt2:              unifieddatalibrary.Float(-2883.540406),
				Yvel:                  unifieddatalibrary.Float(5.291107434),
				YvelAlt1:              unifieddatalibrary.Float(5.27074276),
				YvelAlt2:              unifieddatalibrary.Float(-6.602080212),
				Zaccel:                unifieddatalibrary.Float(-1.06310696),
				Zpos:                  unifieddatalibrary.Float(6167.831808),
				ZposAlt1:              unifieddatalibrary.Float(6165.55187),
				ZposAlt2:              unifieddatalibrary.Float(6165.55187),
				Zvel:                  unifieddatalibrary.Float(-3.356493869),
				ZvelAlt1:              unifieddatalibrary.Float(-3.365155181),
				ZvelAlt2:              unifieddatalibrary.Float(-3.365155181),
			},
			PreGeoLongitude:        unifieddatalibrary.Float(-93.12),
			PreInclination:         unifieddatalibrary.Float(0.0336),
			PrePerigee:             unifieddatalibrary.Float(35786.5),
			PrePeriod:              unifieddatalibrary.Float(1436.12),
			PrePosX:                unifieddatalibrary.Float(3584.432545),
			PrePosY:                unifieddatalibrary.Float(42028.43245),
			PrePosZ:                unifieddatalibrary.Float(-1.97765),
			PreRaan:                unifieddatalibrary.Float(98.3336),
			PreRadiationPressCoeff: unifieddatalibrary.Float(4.51e-7),
			PreSigmaU:              unifieddatalibrary.Float(0.215),
			PreSigmaV:              unifieddatalibrary.Float(1.97),
			PreSigmaW:              unifieddatalibrary.Float(0.208),
			PreSma:                 unifieddatalibrary.Float(42165.1),
			PreVelX:                unifieddatalibrary.Float(-2.543266),
			PreVelY:                unifieddatalibrary.Float(0.24876),
			PreVelZ:                unifieddatalibrary.Float(0.0067352),
			ReportTime:             unifieddatalibrary.Time(time.Now()),
			SatNo:                  unifieddatalibrary.Int(12),
			SourcedData:            []string{"SOURCEDDATA-ID", "SOURCEDDATA-ID"},
			SourcedDataTypes:       []string{"EO", "RADAR"},
			StateModel:             unifieddatalibrary.String("Example name"),
			StateModelVersion:      unifieddatalibrary.Float(3),
			Status:                 unifieddatalibrary.String("POSSIBLE"),
			Tags:                   []string{"PROVIDER_TAG1", "PROVIDERTAG2"},
			TotalBurnTime:          unifieddatalibrary.Float(600.72),
			TransactionID:          unifieddatalibrary.String("TRANSACTION-ID"),
			Uct:                    unifieddatalibrary.Bool(false),
		}},
	})
	if err != nil {
		var apierr *unifieddatalibrary.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}
