// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package unifieddatalibrary

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apijson"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/requestconfig"
	"github.com/stainless-sdks/unifieddatalibrary-go/option"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/param"
)

// ObservationSwirService contains methods and other services that help with
// interacting with the unifieddatalibrary API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewObservationSwirService] method instead.
type ObservationSwirService struct {
	Options []option.RequestOption
}

// NewObservationSwirService generates a new service that applies the given options
// to each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewObservationSwirService(opts ...option.RequestOption) (r ObservationSwirService) {
	r = ObservationSwirService{}
	r.Options = opts
	return
}

// Service operation to take a list of SWIR records as a POST body and ingest into
// the database. This operation is intended to be used for automated feeds into
// UDL. A specific role is required to perform this service operation. Please
// contact the UDL team for assistance.
func (r *ObservationSwirService) UnvalidatedPublish(ctx context.Context, body ObservationSwirUnvalidatedPublishParams, opts ...option.RequestOption) (err error) {
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "")}, opts...)
	path := "filedrop/swir"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return
}

type ObservationSwirUnvalidatedPublishParams struct {
	Body []ObservationSwirUnvalidatedPublishParamsBody
	paramObj
}

// IsPresent returns true if the field's value is not omitted and not the JSON
// "null". To check if this field is omitted, use [param.IsOmitted].
func (f ObservationSwirUnvalidatedPublishParams) IsPresent() bool {
	return !param.IsOmitted(f) && !f.IsNull()
}

func (r ObservationSwirUnvalidatedPublishParams) MarshalJSON() (data []byte, err error) {
	return json.Marshal(r.Body)
}

// Data representing observed short wave infrared (SWIR) measurements.
//
// The properties ClassificationMarking, DataMode, Source, Ts are required.
type ObservationSwirUnvalidatedPublishParamsBody struct {
	// Classification marking of the data in IC/CAPCO Portion-marked format.
	ClassificationMarking string `json:"classificationMarking,required"`
	// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
	//
	// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
	// may include both real and simulated data.
	//
	// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
	// events, and analysis.
	//
	// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
	// datasets.
	//
	// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
	// requirements, and for validating technical, functional, and performance
	// characteristics.
	//
	// Any of "REAL", "TEST", "SIMULATED", "EXERCISE".
	DataMode string `json:"dataMode,omitzero,required"`
	// Source of the data.
	Source string `json:"source,required"`
	// Data timestamp in ISO8601 UTC format.
	Ts time.Time `json:"ts,required" format:"date-time"`
	// Unique identifier of the record, auto-generated by the system.
	ID param.Opt[string] `json:"id,omitzero"`
	// User comments concerning sensor or data limitations.
	BadWave param.Opt[string] `json:"badWave,omitzero"`
	// Time the row was created in the database, auto-populated by the system.
	CreatedAt param.Opt[time.Time] `json:"createdAt,omitzero" format:"date-time"`
	// Application user who created the row in the database, auto-populated by the
	// system.
	CreatedBy param.Opt[string] `json:"createdBy,omitzero"`
	// Unique identifier of the target on-orbit object.
	IDOnOrbit param.Opt[string] `json:"idOnOrbit,omitzero"`
	// Spacecraft WGS84 latitude, in degrees at obTime. -90 to 90 degrees (negative
	// values south of equator).
	Lat param.Opt[float64] `json:"lat,omitzero"`
	// Location/name of the observing sensor.
	LocationName param.Opt[string] `json:"locationName,omitzero"`
	// Spacecraft WGS84 longitude at ob time, in degrees. -180 to 180 degrees (negative
	// values west of Prime Meridian).
	Lon param.Opt[float64] `json:"lon,omitzero"`
	// Originating system or organization which produced the data, if different from
	// the source. The origin may be different than the source if the source was a
	// mediating system which forwarded the data on behalf of the origin system. If
	// null, the source may be assumed to be the origin.
	Origin param.Opt[string] `json:"origin,omitzero"`
	// The originating source network on which this record was created, auto-populated
	// by the system.
	OrigNetwork param.Opt[string] `json:"origNetwork,omitzero"`
	// Original object ID or Catalog Number provided by source.
	OrigObjectID param.Opt[string] `json:"origObjectId,omitzero"`
	// Satellite/catalog number of the target on-orbit object.
	SatNo param.Opt[int64] `json:"satNo,omitzero"`
	// The angle, in degrees, between the target-to-observer vector and the
	// target-to-sun vector.
	SolarPhaseAngle param.Opt[float64] `json:"solarPhaseAngle,omitzero"`
	// Array of absolute flux measurement data, in Watts per square centimeter per
	// micron. This array should correspond with the same-sized array of wavelengths.
	AbsFluxes []float64 `json:"absFluxes,omitzero"`
	// Array of flux ratio data. This array should correspond with the same-sized array
	// of ratioWavelengths.
	FluxRatios []float64 `json:"fluxRatios,omitzero"`
	// Array of ratio wavelength data. This array should correspond with the same-sized
	// array of fluxRatios.
	RatioWavelengths []float64 `json:"ratioWavelengths,omitzero"`
	// Array of wavelengths, in microns. This array should correspond with the
	// same-sized array of absFluxes.
	Wavelengths []float64 `json:"wavelengths,omitzero"`
	paramObj
}

// IsPresent returns true if the field's value is not omitted and not the JSON
// "null". To check if this field is omitted, use [param.IsOmitted].
func (f ObservationSwirUnvalidatedPublishParamsBody) IsPresent() bool {
	return !param.IsOmitted(f) && !f.IsNull()
}
func (r ObservationSwirUnvalidatedPublishParamsBody) MarshalJSON() (data []byte, err error) {
	type shadow ObservationSwirUnvalidatedPublishParamsBody
	return param.MarshalObject(r, (*shadow)(&r))
}

func init() {
	apijson.RegisterFieldValidator[ObservationSwirUnvalidatedPublishParamsBody](
		"DataMode", false, "REAL", "TEST", "SIMULATED", "EXERCISE",
	)
}
