// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package unifieddatalibrary

import (
	"context"
	"net/http"
	"net/url"
	"time"

	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apijson"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apiquery"
	"github.com/stainless-sdks/unifieddatalibrary-go/internal/requestconfig"
	"github.com/stainless-sdks/unifieddatalibrary-go/option"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/param"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/respjson"
)

// SensorCalibrationHistoryService contains methods and other services that help
// with interacting with the unifieddatalibrary API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewSensorCalibrationHistoryService] method instead.
type SensorCalibrationHistoryService struct {
	Options []option.RequestOption
}

// NewSensorCalibrationHistoryService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewSensorCalibrationHistoryService(opts ...option.RequestOption) (r SensorCalibrationHistoryService) {
	r = SensorCalibrationHistoryService{}
	r.Options = opts
	return
}

// Service operation to return the count of records satisfying the specified query
// parameters. This operation is useful to determine how many records pass a
// particular query criteria without retrieving large amounts of data. See the
// queryhelp operation (/udl/&lt;datatype&gt;/queryhelp) for more details on
// valid/required query parameter information.
func (r *SensorCalibrationHistoryService) Count(ctx context.Context, query SensorCalibrationHistoryCountParams, opts ...option.RequestOption) (res *string, err error) {
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	path := "udl/sensorcalibration/history/count"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// Service operation to dynamically query historical data by a variety of query
// parameters not specified in this API documentation. See the queryhelp operation
// (/udl/&lt;datatype&gt;/queryhelp) for more details on valid/required query
// parameter information.
func (r *SensorCalibrationHistoryService) Query(ctx context.Context, query SensorCalibrationHistoryQueryParams, opts ...option.RequestOption) (res *[]SensorCalibrationHistoryQueryResponse, err error) {
	opts = append(r.Options[:], opts...)
	path := "udl/sensorcalibration/history"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// Service operation to dynamically query historical data by a variety of query
// parameters not specified in this API documentation, then write that data to the
// Secure Content Store. See the queryhelp operation
// (/udl/&lt;datatype&gt;/queryhelp) for more details on valid/required query
// parameter information.
func (r *SensorCalibrationHistoryService) WriteAodr(ctx context.Context, query SensorCalibrationHistoryWriteAodrParams, opts ...option.RequestOption) (err error) {
	opts = append(r.Options[:], opts...)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "")}, opts...)
	path := "udl/sensorcalibration/history/aodr"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, nil, opts...)
	return
}

// The Sensor Calibration service records data about a sensor's overall accuracy
// and is used to adjust sensor settings to achieve and maintain that accuracy in
// reported sensor observations. Calibration occurs periodically when needed to
// maintain sensor accuracy or on-demand to adjust a sensor for a specific reading.
type SensorCalibrationHistoryQueryResponse struct {
	// Classification marking of the data in IC/CAPCO Portion-marked format.
	ClassificationMarking string `json:"classificationMarking,required"`
	// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
	//
	// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
	// may include both real and simulated data.
	//
	// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
	// events, and analysis.
	//
	// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
	// datasets.
	//
	// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
	// requirements, and for validating technical, functional, and performance
	// characteristics.
	//
	// Any of "REAL", "TEST", "SIMULATED", "EXERCISE".
	DataMode SensorCalibrationHistoryQueryResponseDataMode `json:"dataMode,required"`
	// Unique identifier of the sensor to which this calibration data applies. This ID
	// can be used to obtain additional information on a sensor using the 'get by ID'
	// operation (e.g. /udl/sensor/{id}). For example, the sensor with idSensor = abc
	// would be queried as /udl/sensor/abc.
	IDSensor string `json:"idSensor,required"`
	// Source of the data.
	Source string `json:"source,required"`
	// Calibration data span start time in ISO 8601 UTC format with millisecond
	// precision.
	StartTime time.Time `json:"startTime,required" format:"date-time"`
	// Unique identifier of the record, auto-generated by the system if not provided on
	// create operations.
	ID string `json:"id"`
	// Sensor azimuth/right-ascension acceleration bias rate, in degrees per second
	// squared, during sensor operation.
	AzRaAccelBias float64 `json:"azRaAccelBias"`
	// Standard deviation azimuth/right-ascension acceleration bias rate, in degrees
	// per second squared.
	AzRaAccelSigma float64 `json:"azRaAccelSigma"`
	// Sensor azimuth/right-ascension bias, in degrees, during sensor operation.
	AzRaBias float64 `json:"azRaBias"`
	// Sensor azimuth/right-ascension bias rate, in degrees per second, during sensor
	// operation.
	AzRaBiasRate float64 `json:"azRaBiasRate"`
	// The mean azimuth/right-ascension average, in degrees, for the duration span.
	AzRaMean float64 `json:"azRaMean"`
	// The root mean square of the azimuth/right-ascension, in degrees, for the
	// duration span.
	AzRaRms float64 `json:"azRaRms"`
	// Standard deviation azimuth/right-ascension bias rate, in degrees per second.
	AzRaSigmaRate float64 `json:"azRaSigmaRate"`
	// Specifies the calibration reference angle set for this calibration data set.
	// Azimuth and Elevation (AZEL) or Right Ascension and Declination (RADEC).
	CalAngleRef string `json:"calAngleRef"`
	// Specifies that the calibration data are from INTRA_TRACK or INTER_TRACK
	// residuals.
	CalTrackMode string `json:"calTrackMode"`
	// The basis of calibration values contained in this record (COMPUTED,
	// OPERATIONAL).
	CalType string `json:"calType"`
	// The confidence noise bias of the duration span.
	ConfidenceNoiseBias float64 `json:"confidenceNoiseBias"`
	// Time the row was created in the database, auto-populated by the system.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Application user who created the row in the database, auto-populated by the
	// system.
	CreatedBy string `json:"createdBy"`
	// Duration of the sensor calibration data which produced these values, measured in
	// days.
	Duration float64 `json:"duration"`
	// Three element array, expressing the sensor location in Earth Centered Rotating
	// (ECR) coordinates, in kilometers. The array element order is [x, y, z].
	Ecr []float64 `json:"ecr"`
	// Sensor elevation/declination acceleration bias rate, in degrees per second
	// squared, during sensor operation.
	ElDecAccelBias float64 `json:"elDecAccelBias"`
	// Standard deviation elevation/declination acceleration bias rate, in degrees per
	// second squared.
	ElDecAccelSigma float64 `json:"elDecAccelSigma"`
	// Sensor elevation/declination bias, in degrees, during sensor operation.
	ElDecBias float64 `json:"elDecBias"`
	// Sensor elevation/declination bias rate, in degrees per second, during sensor
	// operation.
	ElDecBiasRate float64 `json:"elDecBiasRate"`
	// The mean elevation/declination residuals, in degrees, for the duration span.
	ElDecMean float64 `json:"elDecMean"`
	// The root mean square of the elevation/declination, in degrees, for the duration
	// span.
	ElDecRms float64 `json:"elDecRms"`
	// Standard deviation elevation/declination bias rate, in degrees per second.
	ElDecSigmaRate float64 `json:"elDecSigmaRate"`
	// Calibration data span end time in ISO 8601 UTC format with millisecond
	// precision. If provided, the endTime must be greater than or equal to the
	// startTime in the SensorCalibration record.
	EndTime time.Time `json:"endTime" format:"date-time"`
	// The number of observables used in determining the azimuth or right-ascension
	// calibration values.
	NumAzRaObs int64 `json:"numAzRaObs"`
	// The number of observables used in determining the elevation or declination
	// calibration values.
	NumElDecObs int64 `json:"numElDecObs"`
	// The total number of observables available over the calibration span.
	NumObs int64 `json:"numObs"`
	// The number of observables used in determining the photometric calibration
	// values.
	NumPhotoObs int64 `json:"numPhotoObs"`
	// The number of observables used in determining the range calibration values.
	NumRangeObs int64 `json:"numRangeObs"`
	// The number of observables used in determining the range rate calibration values.
	NumRangeRateObs int64 `json:"numRangeRateObs"`
	// The number of observables used in determining the radar cross section (RCS)
	// calibration values.
	NumRcsObs int64 `json:"numRcsObs"`
	// The number of observables used in determining the time calibration values.
	NumTimeObs int64 `json:"numTimeObs"`
	// The total number of tracks available over the calibration span.
	NumTracks int64 `json:"numTracks"`
	// Originating system or organization which produced the data, if different from
	// the source. The origin may be different than the source if the source was a
	// mediating system which forwarded the data on behalf of the origin system. If
	// null, the source may be assumed to be the origin.
	Origin string `json:"origin"`
	// The originating source network on which this record was created, auto-populated
	// by the system.
	OrigNetwork string `json:"origNetwork"`
	// The photometric observation noise bias in visual magnitude.
	PhotoBias float64 `json:"photoBias"`
	// The photometric observation noise standard deviation in visual magnitude.
	PhotoSigma float64 `json:"photoSigma"`
	// Sensor range rate bias acceleration, in kilometers per second squared, during
	// sensor operation.
	RangeAccelBias float64 `json:"rangeAccelBias"`
	// Standard deviation range rate bias acceleration, in kilometers per second
	// squared.
	RangeAccelSigma float64 `json:"rangeAccelSigma"`
	// Sensor range bias, in kilometers, for the duration span.
	RangeBias float64 `json:"rangeBias"`
	// Sensor range rate bias, in kilometers per second for the duration span.
	RangeRateBias float64 `json:"rangeRateBias"`
	// The root mean square of the calibration sensor range rate, in kilometers per
	// second, for the duration span.
	RangeRateRms float64 `json:"rangeRateRms"`
	// Standard deviation range rate, in kilometers per second, for the duration span.
	RangeRateSigma float64 `json:"rangeRateSigma"`
	// The root mean square of the calibration sensor range, in kilometers, for the
	// duration span.
	RangeRms float64 `json:"rangeRms"`
	// Calibration standard deviation range, in kilometers, for the duration span.
	RangeSigma float64 `json:"rangeSigma"`
	// The radar cross section (RCS) observation noise bias in square meters.
	RcsBias float64 `json:"rcsBias"`
	// The radar cross section (RCS) observation noise standard deviation in square
	// meters.
	RcsSigma float64 `json:"rcsSigma"`
	// Array of the catalog IDs of the reference targets used in the calibration.
	RefTargets []string `json:"refTargets"`
	// The reference type used in the calibration.
	RefType string `json:"refType"`
	// The sensor type (MECHANICAL, OPTICAL, PHASED ARRAY, RF).
	SenType string `json:"senType"`
	// The source data library from which this record was received. This could be a
	// remote or tactical UDL or another data library. If null, the record should be
	// assumed to have originated from the primary Enterprise UDL.
	SourceDl string `json:"sourceDL"`
	// Sensor time bias, in seconds, for the duration span.
	TimeBias float64 `json:"timeBias"`
	// Standard deviation time, in seconds, for the duration span.
	TimeBiasSigma float64 `json:"timeBiasSigma"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ClassificationMarking respjson.Field
		DataMode              respjson.Field
		IDSensor              respjson.Field
		Source                respjson.Field
		StartTime             respjson.Field
		ID                    respjson.Field
		AzRaAccelBias         respjson.Field
		AzRaAccelSigma        respjson.Field
		AzRaBias              respjson.Field
		AzRaBiasRate          respjson.Field
		AzRaMean              respjson.Field
		AzRaRms               respjson.Field
		AzRaSigmaRate         respjson.Field
		CalAngleRef           respjson.Field
		CalTrackMode          respjson.Field
		CalType               respjson.Field
		ConfidenceNoiseBias   respjson.Field
		CreatedAt             respjson.Field
		CreatedBy             respjson.Field
		Duration              respjson.Field
		Ecr                   respjson.Field
		ElDecAccelBias        respjson.Field
		ElDecAccelSigma       respjson.Field
		ElDecBias             respjson.Field
		ElDecBiasRate         respjson.Field
		ElDecMean             respjson.Field
		ElDecRms              respjson.Field
		ElDecSigmaRate        respjson.Field
		EndTime               respjson.Field
		NumAzRaObs            respjson.Field
		NumElDecObs           respjson.Field
		NumObs                respjson.Field
		NumPhotoObs           respjson.Field
		NumRangeObs           respjson.Field
		NumRangeRateObs       respjson.Field
		NumRcsObs             respjson.Field
		NumTimeObs            respjson.Field
		NumTracks             respjson.Field
		Origin                respjson.Field
		OrigNetwork           respjson.Field
		PhotoBias             respjson.Field
		PhotoSigma            respjson.Field
		RangeAccelBias        respjson.Field
		RangeAccelSigma       respjson.Field
		RangeBias             respjson.Field
		RangeRateBias         respjson.Field
		RangeRateRms          respjson.Field
		RangeRateSigma        respjson.Field
		RangeRms              respjson.Field
		RangeSigma            respjson.Field
		RcsBias               respjson.Field
		RcsSigma              respjson.Field
		RefTargets            respjson.Field
		RefType               respjson.Field
		SenType               respjson.Field
		SourceDl              respjson.Field
		TimeBias              respjson.Field
		TimeBiasSigma         respjson.Field
		ExtraFields           map[string]respjson.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SensorCalibrationHistoryQueryResponse) RawJSON() string { return r.JSON.raw }
func (r *SensorCalibrationHistoryQueryResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
//
// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
// may include both real and simulated data.
//
// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
// events, and analysis.
//
// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
// datasets.
//
// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
// requirements, and for validating technical, functional, and performance
// characteristics.
type SensorCalibrationHistoryQueryResponseDataMode string

const (
	SensorCalibrationHistoryQueryResponseDataModeReal      SensorCalibrationHistoryQueryResponseDataMode = "REAL"
	SensorCalibrationHistoryQueryResponseDataModeTest      SensorCalibrationHistoryQueryResponseDataMode = "TEST"
	SensorCalibrationHistoryQueryResponseDataModeSimulated SensorCalibrationHistoryQueryResponseDataMode = "SIMULATED"
	SensorCalibrationHistoryQueryResponseDataModeExercise  SensorCalibrationHistoryQueryResponseDataMode = "EXERCISE"
)

type SensorCalibrationHistoryCountParams struct {
	// Calibration data span start time in ISO 8601 UTC format with millisecond
	// precision. (YYYY-MM-DDTHH:MM:SS.sssZ)
	StartTime   time.Time        `query:"startTime,required" format:"date-time" json:"-"`
	FirstResult param.Opt[int64] `query:"firstResult,omitzero" json:"-"`
	MaxResults  param.Opt[int64] `query:"maxResults,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [SensorCalibrationHistoryCountParams]'s query parameters as
// `url.Values`.
func (r SensorCalibrationHistoryCountParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type SensorCalibrationHistoryQueryParams struct {
	// Calibration data span start time in ISO 8601 UTC format with millisecond
	// precision. (YYYY-MM-DDTHH:MM:SS.sssZ)
	StartTime time.Time `query:"startTime,required" format:"date-time" json:"-"`
	// optional, fields for retrieval. When omitted, ALL fields are assumed. See the
	// queryhelp operation (/udl/&lt;datatype&gt;/queryhelp) for more details on valid
	// query fields that can be selected.
	Columns     param.Opt[string] `query:"columns,omitzero" json:"-"`
	FirstResult param.Opt[int64]  `query:"firstResult,omitzero" json:"-"`
	MaxResults  param.Opt[int64]  `query:"maxResults,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [SensorCalibrationHistoryQueryParams]'s query parameters as
// `url.Values`.
func (r SensorCalibrationHistoryQueryParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type SensorCalibrationHistoryWriteAodrParams struct {
	// Calibration data span start time in ISO 8601 UTC format with millisecond
	// precision. (YYYY-MM-DDTHH:MM:SS.sssZ)
	StartTime time.Time `query:"startTime,required" format:"date-time" json:"-"`
	// optional, fields for retrieval. When omitted, ALL fields are assumed. See the
	// queryhelp operation (/udl/&lt;datatype&gt;/queryhelp) for more details on valid
	// query fields that can be selected.
	Columns     param.Opt[string] `query:"columns,omitzero" json:"-"`
	FirstResult param.Opt[int64]  `query:"firstResult,omitzero" json:"-"`
	MaxResults  param.Opt[int64]  `query:"maxResults,omitzero" json:"-"`
	// optional, notification method for the created file link. When omitted, EMAIL is
	// assumed. Current valid values are: EMAIL, SMS.
	Notification param.Opt[string] `query:"notification,omitzero" json:"-"`
	// optional, field delimiter when the created file is not JSON. Must be a single
	// character chosen from this set: (',', ';', ':', '|'). When omitted, "," is used.
	// It is strongly encouraged that your field delimiter be a character unlikely to
	// occur within the data.
	OutputDelimiter param.Opt[string] `query:"outputDelimiter,omitzero" json:"-"`
	// optional, output format for the file. When omitted, JSON is assumed. Current
	// valid values are: JSON and CSV.
	OutputFormat param.Opt[string] `query:"outputFormat,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [SensorCalibrationHistoryWriteAodrParams]'s query parameters
// as `url.Values`.
func (r SensorCalibrationHistoryWriteAodrParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
