// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package unifieddatalibrary

import (
	"time"

	"github.com/stainless-sdks/unifieddatalibrary-go/internal/apijson"
	"github.com/stainless-sdks/unifieddatalibrary-go/option"
	"github.com/stainless-sdks/unifieddatalibrary-go/packages/resp"
	"github.com/stainless-sdks/unifieddatalibrary-go/shared"
)

// UdlRadarobservationHistoryService contains methods and other services that help
// with interacting with the unifieddatalibrary API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewUdlRadarobservationHistoryService] method instead.
type UdlRadarobservationHistoryService struct {
	Options []option.RequestOption
}

// NewUdlRadarobservationHistoryService generates a new service that applies the
// given options to each request. These options are applied after the parent
// client's options (if there is one), and before any request-specific options.
func NewUdlRadarobservationHistoryService(opts ...option.RequestOption) (r UdlRadarobservationHistoryService) {
	r = UdlRadarobservationHistoryService{}
	r.Options = opts
	return
}

// Model representation of observation data for radar based sensor phenomenologies.
// J2000 is the preferred coordinate frame for all observations, but in some cases
// observations may be in another frame depending on the provider. Please see the
// 'Discover' tab in the storefront to confirm coordinate frames by data provider.
type RadarobservationFull struct {
	// Classification marking of the data in IC/CAPCO Portion-marked format.
	ClassificationMarking string `json:"classificationMarking,required"`
	// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
	//
	// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
	// may include both real and simulated data.
	//
	// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
	// events, and analysis.
	//
	// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
	// datasets.
	//
	// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
	// requirements, and for validating technical, functional, and performance
	// characteristics.
	//
	// Any of "REAL", "TEST", "SIMULATED", "EXERCISE".
	DataMode RadarobservationFullDataMode `json:"dataMode,required"`
	// Ob detection time in ISO 8601 UTC with microsecond precision.
	ObTime time.Time `json:"obTime,required" format:"date-time"`
	// Source of the data.
	Source string `json:"source,required"`
	// Unique identifier of the record, auto-generated by the system.
	ID string `json:"id"`
	// azimuth angle in degrees and topocentric frame.
	Azimuth float64 `json:"azimuth"`
	// Sensor azimuth angle bias in degrees.
	AzimuthBias float64 `json:"azimuthBias"`
	// Optional flag indicating whether the azimuth value is measured (true) or
	// computed (false). If null, consumers may consult the data provider for
	// information regarding whether the corresponding value is computed or measured.
	AzimuthMeasured bool `json:"azimuthMeasured"`
	// Rate of change of the line of sight azimuth in degrees per second.
	AzimuthRate float64 `json:"azimuthRate"`
	// One sigma uncertainty in the line of sight azimuth angle measurement, in
	// degrees.
	AzimuthUnc float64 `json:"azimuthUnc"`
	// ID of the beam that produced this observation.
	Beam float64 `json:"beam"`
	// Time the row was created in the database, auto-populated by the system.
	CreatedAt time.Time `json:"createdAt" format:"date-time"`
	// Application user who created the row in the database, auto-populated by the
	// system.
	CreatedBy string `json:"createdBy"`
	// Line of sight declination angle in degrees and J2000 coordinate frame.
	Declination float64 `json:"declination"`
	// Optional flag indicating whether the declination value is measured (true) or
	// computed (false). If null, consumers may consult the data provider for
	// information regarding whether the corresponding value is computed or measured.
	DeclinationMeasured bool `json:"declinationMeasured"`
	// Optional source-provided and searchable metadata or descriptor of the data.
	Descriptor string `json:"descriptor"`
	// Corrected doppler measurement in meters per second.
	Doppler float64 `json:"doppler"`
	// One sigma uncertainty in the corrected doppler measurement, in meters/second.
	DopplerUnc float64 `json:"dopplerUnc"`
	// Line of sight elevation in degrees and topocentric frame.
	Elevation float64 `json:"elevation"`
	// Sensor elevation bias in degrees.
	ElevationBias float64 `json:"elevationBias"`
	// Optional flag indicating whether the elevation value is measured (true) or
	// computed (false). If null, consumers may consult the data provider for
	// information regarding whether the corresponding value is computed or measured.
	ElevationMeasured bool `json:"elevationMeasured"`
	// Rate of change of the line of sight elevation in degrees per second.
	ElevationRate float64 `json:"elevationRate"`
	// One sigma uncertainty in the line of sight elevation angle measurement, in
	// degrees.
	ElevationUnc float64 `json:"elevationUnc"`
	// Unique identifier of the target on-orbit object, if correlated.
	IDOnOrbit string `json:"idOnOrbit"`
	// Unique identifier of the reporting sensor.
	IDSensor string `json:"idSensor"`
	// The position of this observation within a track (FENCE, FIRST, IN, LAST,
	// SINGLE). This identifier is optional and, if null, no assumption should be made
	// regarding whether other observations may or may not exist to compose a track.
	ObPosition string `json:"obPosition"`
	// Model object representing on-orbit objects or satellites in the system.
	OnOrbit shared.OnorbitFull `json:"onOrbit"`
	// Originating system or organization which produced the data, if different from
	// the source. The origin may be different than the source if the source was a
	// mediating system which forwarded the data on behalf of the origin system. If
	// null, the source may be assumed to be the origin.
	Origin string `json:"origin"`
	// The originating source network on which this record was created, auto-populated
	// by the system.
	OrigNetwork string `json:"origNetwork"`
	// Optional identifier provided by observation source to indicate the target
	// onorbit object of this observation. This may be an internal identifier and not
	// necessarily a valid satellite number.
	OrigObjectID string `json:"origObjectId"`
	// Optional identifier provided by observation source to indicate the sensor
	// identifier which produced this observation. This may be an internal identifier
	// and not necessarily a valid sensor ID.
	OrigSensorID string `json:"origSensorId"`
	// Radar cross section in meters squared for orthogonal polarization.
	OrthogonalRcs float64 `json:"orthogonalRcs"`
	// one sigma uncertainty in orthogonal polarization Radar Cross Section, in
	// meters^2.
	OrthogonalRcsUnc float64 `json:"orthogonalRcsUnc"`
	// Line of sight right ascension in degrees and J2000 coordinate frame.
	Ra float64 `json:"ra"`
	// Optional flag indicating whether the ra value is measured (true) or computed
	// (false). If null, consumers may consult the data provider for information
	// regarding whether the corresponding value is computed or measured.
	RaMeasured bool `json:"raMeasured"`
	// Target range in km.
	Range float64 `json:"range"`
	// Range accelaration in km/s2.
	RangeAccel float64 `json:"rangeAccel"`
	// One sigma uncertainty in the range acceleration measurement, in
	// kilometers/(second^2).
	RangeAccelUnc float64 `json:"rangeAccelUnc"`
	// Sensor range bias in km.
	RangeBias float64 `json:"rangeBias"`
	// Optional flag indicating whether the range value is measured (true) or computed
	// (false). If null, consumers may consult the data provider for information
	// regarding whether the corresponding value is computed or measured.
	RangeMeasured bool `json:"rangeMeasured"`
	// Rate of change of the line of sight range in km/sec.
	RangeRate float64 `json:"rangeRate"`
	// Optional flag indicating whether the rangeRate value is measured (true) or
	// computed (false). If null, consumers may consult the data provider for
	// information regarding whether the corresponding value is computed or measured.
	RangeRateMeasured bool `json:"rangeRateMeasured"`
	// One sigma uncertainty in the range rate measurement, in kilometers/second.
	RangeRateUnc float64 `json:"rangeRateUnc"`
	// One sigma uncertainty in the range measurement, in kilometers.
	RangeUnc float64 `json:"rangeUnc"`
	// Optional URI location in the document repository of the raw file parsed by the
	// system to produce this record. To download the raw file, prepend
	// https://udl-hostname/scs/download?id= to this value.
	RawFileUri string `json:"rawFileURI"`
	// Radar cross section in meters squared for polarization principal.
	Rcs float64 `json:"rcs"`
	// one sigma uncertainty in principal polarization Radar Cross Section, in
	// meters^2.
	RcsUnc float64 `json:"rcsUnc"`
	// Satellite/Catalog number of the target on-orbit object.
	SatNo int64 `json:"satNo"`
	// The reference frame of the observing sensor state. If the senReferenceFrame is
	// null it is assumed to be J2000.
	//
	// Any of "J2000", "EFG/TDR", "ECR/ECEF", "TEME", "ITRF", "GCRF".
	SenReferenceFrame RadarobservationFullSenReferenceFrame `json:"senReferenceFrame"`
	// Sensor x position in km at obTime (if mobile/onorbit) in the specified
	// senReferenceFrame. If senReferenceFrame is null then J2000 should be assumed.
	Senx float64 `json:"senx"`
	// Sensor y position in km at obTime (if mobile/onorbit) in the specified
	// senReferenceFrame. If senReferenceFrame is null then J2000 should be assumed.
	Seny float64 `json:"seny"`
	// Sensor z position in km at obTime (if mobile/onorbit) in the specified
	// senReferenceFrame. If senReferenceFrame is null then J2000 should be assumed.
	Senz float64 `json:"senz"`
	// Signal to noise ratio, in dB.
	Snr float64 `json:"snr"`
	// The source data library from which this record was received. This could be a
	// remote or tactical UDL or another data library. If null, the record should be
	// assumed to have originated from the primary Enterprise UDL.
	SourceDl string `json:"sourceDL"`
	// Optional array of provider/source specific tags for this data, where each
	// element is no longer than 32 characters, used for implementing data owner
	// conditional access controls to restrict access to the data. Should be left null
	// by data providers unless conditional access controls are coordinated with the
	// UDL team.
	Tags []string `json:"tags"`
	// Optional identifier to indicate the specific tasking which produced this
	// observation.
	TaskID string `json:"taskId"`
	// Sensor timing bias in seconds.
	TimingBias float64 `json:"timingBias"`
	// Optional identifier of the track to which this observation belongs.
	TrackID string `json:"trackId"`
	// The beam type (or tracking state) in use at the time of collection of this
	// observation. Values include:
	//
	// INIT ACQ WITH INIT VALUES: Initial acquisition based on predefined initial
	// values such as position, velocity, or other specific parameters.
	//
	// INIT ACQ: Initial acquisition when no prior information or initial values such
	// as position or velocity are available.
	//
	// TRACKING SINGLE BEAM: Continuously tracks and monitors a single target using one
	// specific radar beam.
	//
	// TRACKING SEQUENTIAL ROVING: Sequentially tracks different targets or areas by
	// "roving" from one sector to the next in a systematic order.
	//
	// SELF ACQ WITH INIT VALUES: Autonomously acquires targets using predefined
	// starting parameters or initial values.
	//
	// SELF ACQ: Automatically detects and locks onto targets without the need for
	// predefined initial settings.
	//
	// NON-TRACKING: Non-tracking.
	TrackingState string `json:"trackingState"`
	// Optional identifier to track a commercial or marketplace transaction executed to
	// produce this data.
	TransactionID string `json:"transactionId"`
	// Read only enumeration specifying the type of observation (e.g. OPTICAL, RADAR,
	// RF, etc).
	Type string `json:"type"`
	// Boolean indicating this observation is part of an uncorrelated track or was
	// unable to be correlated to a known object. This flag should only be set to true
	// by data providers after an attempt to correlate to an on-orbit object was made
	// and failed. If unable to correlate, the 'origObjectId' field may be populated
	// with an internal data provider specific identifier.
	Uct bool `json:"uct"`
	// X position of target in km in J2000 coordinate frame.
	X float64 `json:"x"`
	// X velocity of target in km/sec in J2000 coordinate frame.
	Xvel float64 `json:"xvel"`
	// Y position of target in km in J2000 coordinate frame.
	Y float64 `json:"y"`
	// Y velocity of target in km/sec in J2000 coordinate frame.
	Yvel float64 `json:"yvel"`
	// Z position of target in km in J2000 coordinate frame.
	Z float64 `json:"z"`
	// Z velocity of target in km/sec in J2000 coordinate frame.
	Zvel float64 `json:"zvel"`
	// Metadata for the response, check the presence of optional fields with the
	// [resp.Field.IsPresent] method.
	JSON struct {
		ClassificationMarking resp.Field
		DataMode              resp.Field
		ObTime                resp.Field
		Source                resp.Field
		ID                    resp.Field
		Azimuth               resp.Field
		AzimuthBias           resp.Field
		AzimuthMeasured       resp.Field
		AzimuthRate           resp.Field
		AzimuthUnc            resp.Field
		Beam                  resp.Field
		CreatedAt             resp.Field
		CreatedBy             resp.Field
		Declination           resp.Field
		DeclinationMeasured   resp.Field
		Descriptor            resp.Field
		Doppler               resp.Field
		DopplerUnc            resp.Field
		Elevation             resp.Field
		ElevationBias         resp.Field
		ElevationMeasured     resp.Field
		ElevationRate         resp.Field
		ElevationUnc          resp.Field
		IDOnOrbit             resp.Field
		IDSensor              resp.Field
		ObPosition            resp.Field
		OnOrbit               resp.Field
		Origin                resp.Field
		OrigNetwork           resp.Field
		OrigObjectID          resp.Field
		OrigSensorID          resp.Field
		OrthogonalRcs         resp.Field
		OrthogonalRcsUnc      resp.Field
		Ra                    resp.Field
		RaMeasured            resp.Field
		Range                 resp.Field
		RangeAccel            resp.Field
		RangeAccelUnc         resp.Field
		RangeBias             resp.Field
		RangeMeasured         resp.Field
		RangeRate             resp.Field
		RangeRateMeasured     resp.Field
		RangeRateUnc          resp.Field
		RangeUnc              resp.Field
		RawFileUri            resp.Field
		Rcs                   resp.Field
		RcsUnc                resp.Field
		SatNo                 resp.Field
		SenReferenceFrame     resp.Field
		Senx                  resp.Field
		Seny                  resp.Field
		Senz                  resp.Field
		Snr                   resp.Field
		SourceDl              resp.Field
		Tags                  resp.Field
		TaskID                resp.Field
		TimingBias            resp.Field
		TrackID               resp.Field
		TrackingState         resp.Field
		TransactionID         resp.Field
		Type                  resp.Field
		Uct                   resp.Field
		X                     resp.Field
		Xvel                  resp.Field
		Y                     resp.Field
		Yvel                  resp.Field
		Z                     resp.Field
		Zvel                  resp.Field
		ExtraFields           map[string]resp.Field
		raw                   string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r RadarobservationFull) RawJSON() string { return r.JSON.raw }
func (r *RadarobservationFull) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
//
// EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
// may include both real and simulated data.
//
// REAL:&nbsp;Data collected or produced that pertains to real-world objects,
// events, and analysis.
//
// SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
// datasets.
//
// TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
// requirements, and for validating technical, functional, and performance
// characteristics.
type RadarobservationFullDataMode string

const (
	RadarobservationFullDataModeReal      RadarobservationFullDataMode = "REAL"
	RadarobservationFullDataModeTest      RadarobservationFullDataMode = "TEST"
	RadarobservationFullDataModeSimulated RadarobservationFullDataMode = "SIMULATED"
	RadarobservationFullDataModeExercise  RadarobservationFullDataMode = "EXERCISE"
)

// The reference frame of the observing sensor state. If the senReferenceFrame is
// null it is assumed to be J2000.
type RadarobservationFullSenReferenceFrame string

const (
	RadarobservationFullSenReferenceFrameJ2000   RadarobservationFullSenReferenceFrame = "J2000"
	RadarobservationFullSenReferenceFrameEfgTdr  RadarobservationFullSenReferenceFrame = "EFG/TDR"
	RadarobservationFullSenReferenceFrameEcrEcef RadarobservationFullSenReferenceFrame = "ECR/ECEF"
	RadarobservationFullSenReferenceFrameTeme    RadarobservationFullSenReferenceFrame = "TEME"
	RadarobservationFullSenReferenceFrameItrf    RadarobservationFullSenReferenceFrame = "ITRF"
	RadarobservationFullSenReferenceFrameGcrf    RadarobservationFullSenReferenceFrame = "GCRF"
)
